### ISSUE TITLE
Enable displaying mid-star rating

### ISSUE THREAD

**Issue by p91paul** [JasonLG1979/gnome-shell-extensions-mediaplayer#108]
Some players, like clementine, allows the user to select mid star rating (eg 3.5 stars). Does MPRIS2 allow you to display this?

**Comment by JasonLG1979** [comment]
semi-starred-symbolic ought to do it as far as a half star icon. I just have to figure out how to do the math in js. I'll put this on my list.

**Comment by JasonLG1979** [comment]
I'm closing this as there's no non-stupid complicated way to do it as far as how the buttons would actually function.
