### ISSUE TITLE
Show playstatus in the system-menu

### ISSUE THREAD

**Issue by badcel** [JasonLG1979/gnome-shell-extensions-mediaplayer#213]
If the extension indicator is located in the system menu the current playstatus should be displayed directly in the menu. As in gnome 3.18 it is possible to collapse every entry in the menu. If the entry for the extension is collapsed it is not possible to see wether music is playing or not.

As the other entries in the menu provide dynamic icons to display their current status this extension should also provide these information.

**Comment by eonpatapon** [comment]
Maybe we could use the control icons to indicate the status instead of the generic music icon ?

**Comment by JasonLG1979** [comment]
@badcel hasn't this been implemented since your initial report. Just trying to clear out some bugs so I can figure out what needs fixed and what not.

**Comment by criztovyl** [comment]
I think it's about this, the top icon reflecting the play status but the menu entry icon not:
![sysmen](https://cloud.githubusercontent.com/assets/2174918/22407166/925169dc-e661-11e6-897d-701c84fd6a32.png)

Unsure about my version, it's the latest one from e.g.o.

**Comment by JasonLG1979** [comment]
Right on. That would be a good idea as it would let you know at a relative glance which player is actually playing if you were to forget. I'm not sure why you would forget, but whatever,lol? I'll look into adding that.

**Comment by badcel** [comment]
Right, i tried s.th. like this in my pullrequest #216 , but probably this should be handled independently from the icon in the top bar from gnome-shell.

**Comment by JasonLG1979** [comment]
My only concern is that the panel has the state of the selected/current player but it's not clear which player that is. It might get confusing having so many player statuses. Maybe have an option to show the current players name in the panel?

**Comment by badcel** [comment]
The name of the player is already in the drop down system-menu. This is just about adding small status information to each individual player in case the player is (manually) closed. The "global status" / tray symbol is kind of a different question for me.

**Comment by JasonLG1979** [comment]
I know. But what happens when you have 2 or more players open in the same state? (paused or stopped I would assume) in that case the added information actually just adds to the confusion. Which player will get the mouse wheel action?

**Comment by badcel** [comment]
There is no confusion? If there are 3 players, there are just 3 different entries displayed. Each one could have a spearate status information, like a small square or triangle for playstatus information. If a user collapses all 3 players they stay collapsed. So the user can not see the state of the 3 different players at a glance.

This is not about the tray icon in the gnome shell top bar. This is about the icon in the menu that opens if the user clicks the status menu. Like in the screenshot from @criztovyl

**Comment by JasonLG1979** [comment]
I get that they are separate things. I guess what I'm saying is that we could do better to make it clear which player is the current player. Here's a crude mockup. It shows what it would look like to have the icon you're talking about plus the name of the app in the panel and it also throws a quit button in there, I'm not sure if we can actually put it there? But that's the best place for it IMHO with my current design.
![drawing](https://cloud.githubusercontent.com/assets/6667703/22469783/c21ef0f8-e792-11e6-86a5-5de424ae7da8.png)

**Comment by eonpatapon** [comment]
At the time I was not pleased by the double icon (music + play/pause/stop) in the aggregate menu. It does not line up very well. I think I tried with just the play/pause/stop icons and I found it quite ok.

**Comment by JasonLG1979** [comment]
> At the time I was not pleased by the double icon (music + play/pause/stop) in the aggregate menu. It does not line up very well. I think I tried with just the play/pause/stop icons and I found it quite ok.

Just a status icon could work with the name of the current player. I'm not a fan of just a status icon in the panel. It's rather ambiguous, the generic music icon adds a little bit of context. I really don't mind what we have now as far as a generic icon/cover + status in the panel. Is there a reason why we don't just use the active player's actual real icon in the panel? You'd know for sure which one was active at a glance.

**Comment by eonpatapon** [comment]
I was talking about the menu, not the top panel (not sure it is clear).

I used a symbolic icon to be more consistent with other items. 

As for the current player selection it's based on the status : play > pause > stop. If there is multiple players playing something then it will use the first one we find, but it's an edge case I guess.

**Comment by JasonLG1979** [comment]
> but it's an edge case I guess

Yep, I wouldn't know why you'd have more than one player playing at the same time?

**Comment by criztovyl** [comment]
So, this it what it looks like if you have two players. In this case cmus is playing.
![playtstaus](https://cloud.githubusercontent.com/assets/2174918/22596486/03d5e79a-ea2c-11e6-982f-e51c8b9a3b25.png)

Here some manipulated screenshots:
In this image with the not-well-lined-up play-indicator...
![playtstaus2](https://cloud.githubusercontent.com/assets/2174918/22596485/03ad6bda-ea2c-11e6-87c0-97ff5e7cf9ed.png)
..and here with status icons only.
![playtstaus3b](https://cloud.githubusercontent.com/assets/2174918/22596705/e10525b8-ea2c-11e6-8bb7-52ed4d6718a6.png)
Another solution (playing player with "play", everything else stays the generic music icon)
![playtstaus3](https://cloud.githubusercontent.com/assets/2174918/22596617/879d52ac-ea2c-11e6-9968-0cf607f4a3bd.png)

I'd prefer the last one ^^

**Comment by JasonLG1979** [comment]
If I had to choose I like number 2, the status next to the icon. It's consistent with the panel.

**Comment by JasonLG1979** [comment]
> In this image with the not-well-lined-up play-indicator...

That's been fixed.

![screenshot from 2017-02-03 18-20-55](https://cloud.githubusercontent.com/assets/6667703/22613437/ecef1f6c-ea3d-11e6-8dd4-4cffb2196e20.png)

**Comment by JasonLG1979** [comment]
Somewhat fixed with https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/pull/320

In that PR if the player exposes the DesktopEntry prop, has a symbolic icon and follows convention/spec (DesktopEntry + '-symbolic' = the name of the symbolic icon) then it's icon will be shown in the panel if it's the active player.

**Comment by JasonLG1979** [comment]
@badcel does #320 solve the problem of knowing which player is playing for you?

**Comment by badcel** [comment]
The problem for me was never which player is playing (because normally i only have one). I'm just missing status information for the play status, to get some kind of consistency with the other entries in the menu.

**Comment by JasonLG1979** [comment]
> I'm just missing status information for the play status

Player status is shown in the panel next to the icon. I guess I don't understand what you mean then?

**Comment by JasonLG1979** [comment]
@badcel kinda off point but I recently added ```{playerName}``` to the status text templet among a BUNCH of other changes. Care to test out the latest release and tell me what you think?
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/tag/v0.2.1

**Comment by JasonLG1979** [comment]
I'm going to close this. It's possible but I'd have to basically re-implement PopupSubMenuMenuItem and the result is ugly IMHO. It throws off the alignment of the text in the menu. Even if I change the size of the icon and the position of the text then it looks crowded.

![screenshot from 2017-06-16 11-14-47](https://user-images.githubusercontent.com/6667703/27235136-3d918fea-5285-11e7-82bd-a44c59266b39.png)

**Comment by JasonLG1979** [comment]
![screenshot from 2017-07-18 09-39-09](https://user-images.githubusercontent.com/6667703/28322964-19e3df40-6b9d-11e7-8070-4c6fd5f1f5a6.png)

Implemented as an option in https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/e4dbe1adafc397260803eea194ac1b0fae6d2a38
