### ISSUE TITLE
Unrating songs

### ISSUE THREAD

**Issue by fbruetting** [JasonLG1979/gnome-shell-extensions-mediaplayer#302]
On every player I used in the past, one could click left of the first star for deleting the rating of a song. Could this be made available here, too?

**Comment by JasonLG1979** [comment]
That would basically involve an invisible button on either side of the rating stars. The one on the right would just be there for balance so everything would still center correctly.

**Comment by fb87** [comment]
The rating is left aligned here, so I think some little space (maybe half a star width) should suffice?

**Comment by JasonLG1979** [comment]
As soon as I finish my UI redesign and it's signed off on it will be centered. See: https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/issues/298

**Comment by fb87** [comment]
I don't think there's a problem with added invisible buttons left and right. Have I missed something?

**Comment by fb87** [comment]
I just recognized that clicking on the current rating de-rates the song. This is also nice, but sadly doesn't work in Lollypop.

**Comment by JasonLG1979** [comment]
>I don't think there's a problem with added invisible buttons left and right. Have I missed something?

No, I never said anything against it? Simply adding a couple buttons is certainly possible...

> I just recognized that clicking on the current rating de-rates the song. This is also nice, but sadly doesn't work in Lollypop.

...But the ability to set ratings is not a part of the MPRIS2 spec. It requires app specific code. I'm not a Lollypop user so I won't be personally be doing it, so unless you do it yourself or talk someone else into it the functionality will remain as it is.

**Comment by fbruetting** [comment]
Ok, if I got some free time, I'll try to code it.

**Comment by JasonLG1979** [comment]
Closing this as it works fine in Quod Libet. It's an upstream issue with Lollypop.
