### ISSUE TITLE
New e.g.o upload

### ISSUE THREAD

**Issue by eonpatapon** [JasonLG1979/gnome-shell-extensions-mediaplayer#307]
@badcel @JasonLG1979 I'm planning to upload the current version on e.g.o soon.

Will try the current master, and if I see some issues I will report them here.

**Comment by JasonLG1979** [comment]
OK, sounds good.

**Comment by eonpatapon** [comment]
All seems fine to me, will upload it this evening

**Comment by JasonLG1979** [comment]
You need a new screenshot. Here:
![screenshot from 2017-02-02 17-02-06](https://cloud.githubusercontent.com/assets/6667703/22572456/d1a5985a-e969-11e6-8537-30034bd5b948.png)

**Comment by JasonLG1979** [comment]
@eonpatapon the extension could use updated again. Use this screenshot if you would please.
![screenshot](https://cloud.githubusercontent.com/assets/6667703/26285792/23647628-3e1c-11e7-986b-b2f5cd0822b5.png)

**Comment by JasonLG1979** [comment]
@eonpatapon If you'd like I'd love to take ownership/maintainership of this extension and repo if you're not planning on actively maintaining it?

**Comment by eonpatapon** [comment]
@JasonLG1979 yes I think it would be better since I don't use it anymore. I can do a tranfert on github to your account if you want. As for the e.g.o site I'm not sure how to do this. We can try to contact one the admins.

**Comment by JasonLG1979** [comment]
Sounds good. Whenever you're on github and let me know about the extensions site. I do have a question as to how to build a package for the site though is it just building a zip install?

**Comment by eonpatapon** [comment]
You just have to do make zip-file, the zip ends in the zip-files directory. This is what you upload to e.g.o

**Comment by eonpatapon** [comment]
To transfert this repo to your account, you have to remove your fork

**Comment by JasonLG1979** [comment]
OK

**Comment by JasonLG1979** [comment]
Done

**Comment by JasonLG1979** [comment]
@eonpatapon still waiting on you to transfer ownership of the extension on https://extensions.gnome.org.

**Comment by eonpatapon** [comment]
There is nothing I can do on the website. Can you try to contact an
admin ?

**Comment by JasonLG1979** [comment]
I think we have to jump on the mailing list. Kinda stupid they don't have an easier way to do it.

**Comment by JasonLG1979** [comment]
@eonpatapon I sent a request to join the mailing list.

**Comment by JasonLG1979** [comment]
@eonpatapon I've looked far and wide, tried to join a couple different mailing lists and asked on the IRC. I can't figure out how to transfer ownership on  https://extensions.gnome.org. It looks as though I might have to upload my own version. If you would please take the latest release zip and upload it and make a note on https://extensions.gnome.org about the situation in the extension's description. The next time I do a release if the situation hasn't been resolved I'll upload my own version and you can delete/remove your version.

**Comment by JasonLG1979** [comment]
I'd rather have a smooth succession of ownership/maintainership  as not to fragment things and make it a hassle for users but it is what it is I guess?

**Comment by JasonLG1979** [comment]
@TingPing You wouldn't happen to know who I could talk to to transfer ownership of this extension on   https://extensions.gnome.org would you?

**Comment by TingPing** [comment]
No idea, I'll ask on IRC but its the weekend now so might not find anybody until next week.

**Comment by TingPing** [comment]
@JasonLG1979 You are now the owner =)

**Comment by JasonLG1979** [comment]
@TingPing Thanks!!! I guess it helps to know people that know people,lol!!!

**Comment by JasonLG1979** [comment]
@TingPing I was also going to get around submitting a patch to GNOME's default mpris widget.

https://github.com/GNOME/gnome-shell/blob/19816523c7e16dd8b0aef5aaf2f2b9a6e6208760/js/ui/mpris.js#L95-L102

Is no good as it does no error checking and if it fails the old cover is left shown. They'd want to do some error checking when getting a very possibly malformed uri from some random player. Something like this:

https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/src/lib.js#L60-L71

That will use a fallback icon if the uri fails.

**Comment by TingPing** [comment]
Sounds reasonable.

**Comment by JasonLG1979** [comment]
The alternative is GLib.file_test but that's no bueno because some players like Spotify send http uri's and the test locks up the shell until it's done since it's blocking.

**Comment by TingPing** [comment]
With Wayland the Shell blocking up is basically the worst thing ever and I encounter it way too often.

**Comment by JasonLG1979** [comment]
They really need to have an extensions API so they can run in their own threads.

**Comment by TingPing** [comment]
Well, IME it is more complicated than "just throw threads at the problem" and I think that would cause more issues rather than less.

Also having a real extension API also isn't necessarily a pure win because that would mean less features would be exposed or possible.

**Comment by JasonLG1979** [comment]
It's just a bad idea to allow extensions to basically do whatever they want in the same thread as the Shell. I've ran into situations when I'm hacking around on this extension where I had to log into my wife's profile to uninstall the extension because it crashes the shell as soon as I login and just kicked me back out.

**Comment by JasonLG1979** [comment]
I guess what I'd like is more confinement, and auto-disabling of an extension that crashed the shell the last time it tried to run.

**Comment by JasonLG1979** [comment]
@TingPing btw. Pithos ratings is still on my roadmap for this extension. I just can't figure out how I want to do it from a UI standpoint. You can't do right click menus so I'm left with basically a row of buttons. The question then becomes do I use just icons, just words or both?

**Comment by JasonLG1979** [comment]
I purposely set up our ratings interface so that you'll be able to rate the current song and any other song in the tracklist in the extension so you have to consider size. I might to icons and words in the main trackbox and just icons in the tracklist? Your thoughts?

**Comment by TingPing** [comment]
Can you do tooltips? If so icons + tooltips.

**Comment by JasonLG1979** [comment]
I don't think you can anymore. once upon a time you could.

**Comment by JasonLG1979** [comment]
I'm also going to have to use the star icon instead of the heart for love. There is no "non-heart" icon like the non-starred icon.

**Comment by JasonLG1979** [comment]
I'll throw together some mockups.
