### ISSUE TITLE
Customizing position from  top to bottom throws position in different spots when loaded.

### ISSUE THREAD

**Issue by cyberalex4life** [JasonLG1979/gnome-shell-extensions-mediaplayer#329]
Hello, the new top to bottom custom position is putting the player position (default player to start or the player menu) in different spots, especially if there are other extensions that have menus (dynamic menus like shell-volume-mixer). Although I read that the player position can't be successfully put either way then from top to bottom, I think that this procedure should refer to the position of something that stays on aggregate menu allways, like power menu, or user menu. 
I also realize that there will always be complications no matter the method you use.

**Comment by JasonLG1979** [comment]
I agree placement is a problem.

The problem with your suggestion is that many of the default known items are dynamically hidden and shown. For example if you have bluetooth you'll see the bluetooth item if not it's hidden. It wouldn't be very good to have an option that says "always put the extension after the bluetooth item" if it where hidden. I'll see what I can come up with.

**Comment by cyberalex4life** [comment]
Yes, but power or user account? My idea is that it should start with calculating one of these positions and reflect to them. To be honest, I would not eliminate the method that's already implemented, I think this should me more like another option of positioning, because then there would come one that would say hey you changed that, not good. I think I've seen this kind of positioning in bumblebee-status (https://extensions.gnome.org/extension/1100/bumblebee-status/); it calculates Power Settings position and puts the menu just on top of it.

**Comment by cyberalex4life** [comment]
Here's the enable() function:
```
function enable() {
    _bumblebeeIndicator = new BumblebeeIndicator();
    
    let aggregateMenuPanelButton = Main.panel.statusArea['aggregateMenu'];
    let powerIndicator = aggregateMenuPanelButton._power;
    let powerSubmenuPosition = aggregateMenuPanelButton.menu._getMenuItems().indexOf(powerIndicator.menu);
    aggregateMenuPanelButton._indicators.insert_child_below(_bumblebeeIndicator.indicators, powerIndicator.indicators);
    aggregateMenuPanelButton.menu.addMenuItem(_bumblebeeIndicator.menu, powerSubmenuPosition);
}
```

**Comment by JasonLG1979** [comment]
> My idea is that it should start with calculating one of these positions and reflect to them.

That's no better than doing what we already do, that just trades a zero reference for a reference of an item that may or may not actually be visible. The problem is that there's no way to control the order in which extensions are loaded and we only can know about the number of items at the time when we are loaded. Short of continually checking our own menu positions(every player is a separate item) there's no way to know about the positions of extensions that load after us.

Even in the above code there's still nothing from stopping an extension that loads after that one from taking it's place.

**Comment by JasonLG1979** [comment]
OK totally misunderstood what you were talking about. I thought you meant the in the menu.

**Comment by JasonLG1979** [comment]
Even in the above case it's still a best try situation. There's nothing from stopping another extension that loads later from taking that spot.

**Comment by JasonLG1979** [comment]
The natural place I would thing would be next to the sound icon? What do you think? I can try to throw that together...

**Comment by JasonLG1979** [comment]
On second thought putting it by the sound icon looks bad...

```js 
Main.panel.statusArea.aggregateMenu._indicators.insert_child_below(indicator.indicators, Main.panel.statusArea.aggregateMenu._screencast.indicators);```

Puts it to the left of the default indicators and try's it best to make sure it's the 1st non-default indicator in the panel.

**Comment by JasonLG1979** [comment]
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/commit/61d911851f55f031523cfd9e4d20c49f1f26275f

That work for you?

**Comment by cyberalex4life** [comment]
Well, I think I did not make myself understood and this is my fault, I kind of rushed out a bit. It's about the player menu in the aggregate menu. It has to do with desiredMenuPosition. I mangled a bit and did a short-circuit using: 
`    desiredMenuPosition = Main.panel.statusArea.aggregateMenu.menu._getMenuItems().indexOf(Main.panel.statusArea.aggregateMenu._power.menu);
`
I also changed the position of Bumblebee status menu to something like desiredMenuPosition+1. This seems to work for know, but using the Allow to start default mediaplayer still throws it in an upper position, so I'm not using it. Updating desiredMenuPosition on players status (close/open) might help in my case. Anyway, this is something I can settle with.

**Comment by JasonLG1979** [comment]
Might want to put it after rfkill or before the the system menu other extensions dealing with power may want their menus around the power menu

**Comment by cyberalex4life** [comment]
eh I tried, doesn't work well with bumblebee in the menu, saw I just commented everything everything about bumblebee menu in that extension

**Comment by cyberalex4life** [comment]
But just as a question, I only looked quite fast over all the code, but does it calculate some delta_position when things change, because I have seen that in manager.js it relies on desired menu position, and since changes appear, this certainly is not the same. Shouldn't the add of a new player rely on finding the first player position, at least, and then add menu after? I've seen this in the code. Managing first player position should give some sense to adding players. Sometimes SMPlayer comes on top of Audacious (which is the default for me). This doesn't bother me that much, if it doesn't have another menu between them. If I keep it without bumblebee I think it works this way.

**Comment by JasonLG1979** [comment]
> but does it calculate some delta_position when things change,

Each player is a separate menu item. with the exception of the default player which *should* always 1st, each new player is added after the other. So basically the formula is desired menu position + number of players.

It could use some work for sure. I'll see what I can come up with here in a bit.

**Comment by JasonLG1979** [comment]
```js
desiredMenuPosition = Main.panel.statusArea.aggregateMenu.menu._getMenuItems().indexOf(Main.panel.statusArea.aggregateMenu._rfkill.menu) + 1;
```

Should keep it above anything that wants to be by the power menu and make it pretty much the last menu item in the menu besides anything that explicitly wants to be loaded by the power menu and the power menu.

**Comment by JasonLG1979** [comment]
Give this a shot and see if it works for you.
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/tree/AggregateMenu-menu-placement-tweaks

**Comment by JasonLG1979** [comment]
Basically it creates a single instance of our default player placeholder that is always added 1st. When the default player is launched the placeholder is hidden and the real menu takes it's place. Or if the run default setting is toggled it's hidden or shown depending. So your default player should always be 1st(unless maybe if you restart the shell while the player is in the menu things could get goofy then maybe?) The desired position is a getter that uses the index of the _rfkill.menu so it pretty much always put the players above the _rfkill.menu unless you disable and/or enable extensions in the agg menu then I'm not sure what will happen it really depends on where those extensions want to be?

I'm just going to have to write an extension that sets the order of menu items in the agg menu...

**Comment by cyberalex4life** [comment]
This is what I've settled with: 
extension.js
`function enable() {
    -------------
   if (position == Settings.IndicatorPosition.VOLUMEMENU) {
    indicator = new Panel.AggregateMenuIndicator();
    menu = Main.panel.statusArea.aggregateMenu.menu;
    Settings.gsettings.set_int(Settings.MEDIAPLAYER_NUM_MENU_ITEMS_KEY, menu.numMenuItems + 1);
//    desiredMenuPosition = Settings.gsettings.get_int(Settings.MEDIAPLAYER_MENU_POSITION_KEY) - 1; 
    desiredMenuPosition = Main.panel.statusArea.aggregateMenu.menu._getMenuItems().indexOf(Main.panel.statusArea.aggregateMenu._rfkill.menu)+1; // +1 because volume mixer loads harder in the 0-150% volume mode
-------------------
}
``

manager.js
`_addPlayerToMenu: function(isDefaultPlayer, owner) {
      let actualPos;
      if (isDefaultPlayer) {
        if(this._players[owner].player){
            this.desiredMenuPosition = this._getPlayerMenuPosition(this._players[owner].player.ui);
         }
        actualPos = this.desiredMenuPosition;
      }
      else {
        actualPos = this.desiredMenuPosition + this.nbPlayers();
      }    
      this.menu.addMenuItem(this._players[owner].ui, actualPos);
      this._refreshActivePlayer(this._players[owner].player);
    }
`

**Comment by cyberalex4life** [comment]
My conclusions are:

- Volume Mixer should keep all application volume slider in a dropdown menu (requested (not by me), but not implemented)
- Same with media player indicator (aggregate menu mode). A conception of my own could look in 2 ways.

1. 
```
Player(s) Menu:
    First Player (or Default Player)
    --------------------------
    Active Player 
           Player Controls
    Another Player
```
    --------------------------

2. 
Player(s) Menu:
   ------------------------------------------
    First Player (or Default Player)
       ...................................
    **Active Player** 
    Another Player
        ..................................
    ------------------------------------------
    Player Controls
    My conclusions are:

- Volume Mixer should keep all application volume slider in a dropdown menu (requested (not by me), but not implemented)
- Same with media player indicator (aggregate menu mode). A conception of my own could look in 2 ways.

1. 
```
Player(s) Menu:
    First Player (or Default Player)
    ................................
    Active Player 
    --------------------------
    Player Controls
          Player Controls
               Player Controls
    --------------------------
    Another Player
    .................................
```
    

2. 
```
Player(s) Menu:
   ------------------------------------------
    First Player (or Default Player)
       ...................................
    **Active Player** 
    Another Player
        ..................................
    ------------------------------------------
    Player Controls
          Player Controls
               Player Controls
    ------------------------------------------
```

**Comment by cyberalex4life** [comment]
Of course, there are some personal conclusions

**Comment by JasonLG1979** [comment]
did you try my branch?

**Comment by JasonLG1979** [comment]
> Same with media player indicator (aggregate menu mode). A conception of my own could look in 2 ways.

I've thought of that myself but then you end up with menus nested 3 deep with the tracklist and playlists.

**Comment by JasonLG1979** [comment]
Things get weird with nested menus. The GNOME Shell toolkit/UI stack or whatever you call it isn't built at all for nested menus. By default when you open a menu it sends a signal to close all other menus so opening a submenu nested in a menu will close the parent menu (one of the reasons for the ListSubMenu subclass) and it's <b>REALLY</b> bad at deciding when to use/show a scrollbar (the other reason for the ListSubMenu subclass) Menus nested 3 deep would be a PINTA.

**Comment by cyberalex4life** [comment]
I wouldn't produce a nested menu, to say so, I would activate or move controls on active player (at the same level), treat it more as a list. On menu keeping all in, so the sorting would only be inside that menu. All the players inside the menu, only one active (with controls). Or so it's my theory. The question would be if a  clear enough design could be made. I know volume mixer only implements this by bold text in the output sinks menu.

**Comment by cyberalex4life** [comment]
About that link, yeah I downloaded did a git clone and didn't get me that specific branch. I tried it right now, here's what happens:
![menu_002](https://cloud.githubusercontent.com/assets/2423189/23972461/7db62994-09da-11e7-83a8-2dcf039fddcf.jpg)

**Comment by cyberalex4life** [comment]
the second player jumps a position and the third come just comes after. This is happening with or without allow to start active player.

**Comment by JasonLG1979** [comment]
If I had to guess using the getter isn't a good idea.

**Comment by cyberalex4life** [comment]
No wait. I just tried a +1 in getter:
```
get desiredMenuPosition() {
      if (this.inAggregateMenu) {
        return Main.panel.statusArea.aggregateMenu.menu._getMenuItems().indexOf(Main.panel.statusArea.aggregateMenu._rfkill.menu)+1;
      }
      return 0;
    },
```
I don't know why, but it works. In fact, if we want it after _rfkill it should be +1

**Comment by JasonLG1979** [comment]
I want before _rfkill. _rfkill is the "airplane mode" menu. It would look weird to come in under it.

**Comment by JasonLG1979** [comment]
I just amended that branch. Try it now.

**Comment by JasonLG1979** [comment]
What extensions are you using so I can test it out myself?

**Comment by cyberalex4life** [comment]
![menu__03](https://cloud.githubusercontent.com/assets/2423189/23973116/52096362-09dd-11e7-89fd-5b22f4879193.jpg)
![menu__04](https://cloud.githubusercontent.com/assets/2423189/23973117/5496da9c-09dd-11e7-8be6-cdb4c054f115.jpg)
Well to be honest there is where I want it (between wireless and power). I have it there for a long time and I'm used to it. Do you want the extensions that populate the aggregate menu, or all of them (this one is long).

**Comment by JasonLG1979** [comment]
I'd like the ones that go in the menu please.

It's going to be damn near impossible to absolutely put it in exactly where we want it, or for that matter make sure it's in the same order every time. But I want to at least make sure all the players are grouped together.

**Comment by cyberalex4life** [comment]
One must test this +1/-1 hypothesis, This did the trick for me.

**Comment by JasonLG1979** [comment]
If I had to guess why it was messed up it's because other extensions are loaded after and that changes the index of _rfkill. So the getter was returning a different value. Without the getter the starting position doesn't change.

**Comment by cyberalex4life** [comment]
I'm gonna do something outrageous, I've put ~/.local/share/gnome-shell in my dropbox so that you could see exactly what I have: 
https://www.dropbox.com/s/ge6kgpwfwegxd0f/gnome-shell.zip?dl=0
This is my argos tlp indicator (in /~.config/argos: it won't work without pkroot: use gksu, gnomesu, beesu
https://www.dropbox.com/s/nhrra3n0xw509lo/TLP.r.2s.sh?dl=0
In there:

- easystroke-autochangeis an extension that starts a script which switches personal easystroke settings on mouse plug-in/plug-out
- bumblebee-status is modified to always show panel icon and no menu
- prevent-legacy-tray-hotspot modified to show status icons on less effort (faster).
- shell-volume-mixer_reset-step - starts a script which changes step of volume mixer to a value and back (workaround for not being able to load in boost mode with changed step)
An my active extensions are:
![ext_pg1](https://cloud.githubusercontent.com/assets/2423189/23973860/d00309be-09e0-11e7-9921-9a333d28c296.jpg)
![ext_pg2](https://cloud.githubusercontent.com/assets/2423189/23973863/d27159bc-09e0-11e7-91ff-a9545c8bee30.jpg)
![ext_pg3](https://cloud.githubusercontent.com/assets/2423189/23973866/d55f785c-09e0-11e7-901b-98f1bd79b43d.jpg)
![ext_pg4](https://cloud.githubusercontent.com/assets/2423189/23973868/d7ec2476-09e0-11e7-8cb8-faf85973f18f.jpg)

**Comment by cyberalex4life** [comment]
I'm using GnomeShell 3.20 in OpenSuSE 42.2. pkroot is basicly a wrapper for polkit made of 2 scripts and a *.policy.

**Comment by cyberalex4life** [comment]
So in the menu (wasn't paying atention): 
- shell-volume-mixer@derhofbauer.at, 
- mediaplayer@patapon.info
- hibernate-status@dromi
- gnome-shell-extension-bumblebee-status.dsboger@gmail.com (with icon always in the panel, no menu)

**Comment by cyberalex4life** [comment]
I had already tried the branch from two days ago, with not getter, default player comes to the bottom while the others go on top, like this:
![menu_002](https://cloud.githubusercontent.com/assets/2423189/23974936/c47f4e3a-09e6-11e7-9cda-634098e8d190.jpg)

**Comment by cyberalex4life** [comment]
I added: 
`      this.desiredMenuPosition=Main.panel.statusArea.aggregateMenu.menu._getMenuItems().indexOf(Main.panel.statusArea.aggregateMenu._rfkill.menu)+1;`
to `_addPlayerToMenu: function(isDefaultPlayer, owner) ` right before the if, and it works ok, even bumblebee menu works ok.

**Comment by JasonLG1979** [comment]
Well crap I'm running Ubuntu GNOME 17.04 to test on (what will shortly become) GNOME 3.24 and none of those extensions will load from the extensions site... I'll have to build them and change the versions...

**Comment by JasonLG1979** [comment]
*I usefully run the latest stable version of Fedora but since GNOME 3.24 is coming out soon Ubuntu GNOME 17.04 was the easiest way to test it.

**Comment by JasonLG1979** [comment]
To go off on a tangent. Can't say I'm very impressed with Ubuntu 17.04 so far. It throws errors left and right. Even for a Beta it's pretty bad. Logs is also <b>FULL</b> of GNOME Shell errors...

**Comment by cyberalex4life** [comment]
I kind of like bumblebee for now, I tested it and seemed in performance close to the performance I got on windows (the cards I had were: NVidia 310m, 610m, and now 920m). Ubuntu 16.04 breaks badly, can't go to console; 16.10 same, nvidia-prime is broken on gnome-shell for me on 16.04 and 16.10 (or was). Plus I have tried games on nvidia-prime  and did not get as much performance as I should have, very little over bumblebee, and mostly in the begining. So my choice is still bumblebee. nvidia-bumblebee did not compile on kernel 4.9 in Fedora 25. so I got back to OpenSuSE 42.2, where bumblebee works ok. In general Ubuntu seemed to me quite unstable and very easy to break, very easy to install all sorts of stuff without keeping track of what I did. In OpenSuSE you have to be careful with repo's, in Fedora the same. I liked quite much Arch from the perspective of Manjaro until it breaked from upstream and I couldn't login in X11.

**Comment by cyberalex4life** [comment]
I will leave for now, it's 3AM, I'd better get to sleep.

**Comment by JasonLG1979** [comment]
I merged that branch into master. We can go from there.

**Comment by cyberalex4life** [comment]
I've also made this dirty hack: put:
```
function _getDesiredPosition(){
  return Main.panel.statusArea.aggregateMenu.menu._getMenuItems().indexOf(Main.panel.statusArea.aggregateMenu._rfkill.menu)+1;
}
```
in manager.js on top of everything and added imports. Then in extension.js
```
//    desiredMenuPosition = Settings.gsettings.get_int(Settings.MEDIAPLAYER_MENU_POSITION_KEY) - 1;
    desiredMenuPosition = Manager._getDesiredPosition();
```
This works, but feels like scratching right ear with left hand. I'm just starting to learn javascript for web development.

**Comment by JasonLG1979** [comment]
@cyberalex4life could you test the master branch and see if everything works as expected for you. I push a couple more changes.

**Comment by cyberalex4life** [comment]
@JasonLG1979  I tested and it still can't put right new players, mostly after screen lock:


![menu_003](https://cloud.githubusercontent.com/assets/2423189/24072680/5a65abe8-0bf3-11e7-8851-b16563d502e9.jpg)

I would also suggest rfkill +1, because I don't see a point in splitting network menu(with wireless) and bluetooth menu from rfkill (airplane mode) since they are very much related imho.
![menu_002](https://cloud.githubusercontent.com/assets/2423189/24072739/2aa021ee-0bf4-11e7-81f2-33a3ce0b4d22.jpg)

The only solid solution I had found is to update position in 
```
_addPlayerToMenu: function(isDefaultPlayer, owner) {
      let actualPos;
      if(this.menu==Main.panel.statusArea.aggregateMenu.menu){this.desiredMenuPosition=_getDesiredPosition();}
.......................................
}
```
This proved to me very stable.

**Comment by JasonLG1979** [comment]
> I would also suggest rfkill +1, because I don't see a point in splitting network menu(with wireless) and bluetooth menu from rfkill (airplane mode) since they are very much related imho.

OK, I'll change it to rfkill +1.


> _addPlayerToMenu: function(isDefaultPlayer, owner) {
>       let actualPos;
>       if(this.menu==Main.panel.statusArea.aggregateMenu.menu){this.desiredMenuPosition=_getDesiredPosition();}
> .......................................
> }

That's redundant. If it's not in the agg menu the desired position is always 0.

**Comment by JasonLG1979** [comment]
> _getDesiredPosition()

Are you working off master because that's not a function in master?

**Comment by JasonLG1979** [comment]
Changed to rfkill +1. @cyberalex4life can you test the master branch now?

**Comment by JasonLG1979** [comment]
> I tested and it still can't put right new players, mostly after screen lock:

Returning from a locked screen must restart the Shell. I switched back to Fedora 25 so I can install those extensions and test it myself.

**Comment by cyberalex4life** [comment]
@JasonLG1979  I already tested the +1 because in the end after I test what you update, I make changes. I apologize for ambiguity.

My full workaround seems dirty. but it works. Maybe, some day, with a clear head, you'll figure a more natural solution. 

in manager.js
```
........................................
const UI = Me.imports.ui;

const Main = imports.ui.main;
function _getDesiredPosition(){
  return Main.panel.statusArea.aggregateMenu.menu._getMenuItems().indexOf(Main.panel.statusArea.aggregateMenu._rfkill.menu)+1;
}
...............................................
_addPlayerToMenu: function(isDefaultPlayer, owner) {
      let actualPos;
      if(this.menu==Main.panel.statusArea.aggregateMenu.menu){this.desiredMenuPosition=_getDesiredPosition();}
      if (isDefaultPlayer) {
        actualPos = this.desiredMenuPosition;
      }
      else {
        actualPos = this.desiredMenuPosition + this.nbPlayers() -1;
      }    
      this.menu.addMenuItem(this._players[owner].ui, actualPos);
      this._refreshActivePlayer(this._players[owner].player);
    },
.....................
```
in extension.js
```
..............................
if (position == Settings.IndicatorPosition.VOLUMEMENU) {
    indicator = new Panel.AggregateMenuIndicator();
    menu = Main.panel.statusArea.aggregateMenu.menu;
    Settings.gsettings.set_int(Settings.MEDIAPLAYER_NUM_MENU_ITEMS_KEY, menu.numMenuItems + 1);
//    desiredMenuPosition = Settings.gsettings.get_int(Settings.MEDIAPLAYER_MENU_POSITION_KEY) - 1; 
    desiredMenuPosition = Manager._getDesiredPosition();
  }
.........................
```
I did not treat  the other cases. because, when you switch to center or right indicator, things work actually all right. Maybe it's something I again missed to declare, my bad, I was tired these days.

**Comment by cyberalex4life** [comment]
For some reason, refreshing the value of desiredPosition for aggregate menu seems the best. Actually I noticed something when restarting gnome-shell, it's probably from volume mixer, the menu looks like it's expanding much more then it needs to, then it comes to the desired shape. (That's probably why there's this discrepancy in the status menu option.)
It might that the old volume slider fails to be removed just in time. This happened mostly after I've made some extension updates, bumblebee-status, volume-mixer and the one we're trying to make right. I'll have to take a look at the change log from volume mixer.

**Comment by JasonLG1979** [comment]
@cyberalex4life I've installed the volume-mixer and hibernate-status extensions and even after I restart the shell or return from a locked screen I can not reproduce your problem with the current master.(I can't install the bumblebee extension it throws an error as I don't have dual graphics cards)

> I already tested the +1 because in the end after I test what you update, I make changes. I apologize for ambiguity.

The current master does more than that. As I've said before, we were creating and destroying the default player placeholder. The current master now only creates it once, and hides or shows it as needed. As far as placement goes we really can't guarantee that the starting index is always the same because as you know we can't control the order in which extensions are loaded. But in the current master all the players should at least be grouped together.

I really wish you would actually test the current master...

**Comment by JasonLG1979** [comment]
![screenshot from 2017-03-18 16-48-50](https://cloud.githubusercontent.com/assets/6667703/24076370/8a4ebba2-0bfc-11e7-907a-dfe7556543d8.png)

**Comment by JasonLG1979** [comment]
Correction: My bad the problem was with mater was most likely:
```js
actualPos = this.desiredMenuPosition + this.nbPlayers(); -1
```
Fixed it think?

**Comment by cyberalex4life** [comment]
I tried the modification. 

When Airplane Mode (or bluetooth) menu comes on, things get messed up. I also tried even before the `..(); -1` which does work great with center or right, not with status menu though. Let's call it a draw for now. We don't know exactly where the problem is. I know fedora works slicker, faster, it might be just OpenSuSE which uses some of it's own optimizations (I recall something with 42.1), or it might be a mess from my configuration. Certainly this needs more testing on other distro's, and in the it end the fault might still be on my side. Let's just wait for now.

**Comment by JasonLG1979** [comment]
Agreed. Extensions are the redheaded step child of the Shell. The Shell basically just provides a means to load them and that's about it. Beyond that it's pretty much the wild west. There are several things that could be improved. A long with the whole ordering thing another REALLY, REALLY stupid thing is that the extensions share the same event loop as the Shell and have access to everything in the Shell. They are basically just scabbed in. The result is that an extension can block and/or crash the entire Shell. And even after a misbehaving extension crashes the Shell if/when the Shell restarts it does nothing to disable said misbehaving extension. It will just reload the misbehaving extension and wait for it to crash the Shell again. It's up to the user to figure out which extension is causing the problem.

**Comment by JasonLG1979** [comment]
@cyberalex4life I have a PR in that removes the default player option altogether as the ability to launch a default player is redundant since it can be done with as many or less clicks elsewhere. When/if it hits can you test it out and see if things are a little more consistent as far as player placement?

**Comment by cyberalex4life** [comment]
Yes, I can

**Comment by JasonLG1979** [comment]
You want to give this branch a try? https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/tree/remove-default-player

**Comment by cyberalex4life** [comment]
Well, positions are still messed up, when locking and unlocking the screen, when switching from center/right to aggregate menu:
![screenshot from 2017-04-27 11-08-05](https://cloud.githubusercontent.com/assets/2423189/25474337/883f7db6-2b3b-11e7-8fcd-527b2d943553.png)
![screenshot from 2017-04-27 11-08-23](https://cloud.githubusercontent.com/assets/2423189/25474340/8af628ac-2b3b-11e7-8588-1a13c7cad395.png)
![screenshot from 2017-04-27 11-09-11](https://cloud.githubusercontent.com/assets/2423189/25474344/8db37c84-2b3b-11e7-9344-de862cb694b3.png)
![screenshot from 2017-04-27 11-09-23](https://cloud.githubusercontent.com/assets/2423189/25474346/8fb3e96a-2b3b-11e7-8d2a-0239ffdd4a67.png)
![screenshot from 2017-04-27 11-10-27](https://cloud.githubusercontent.com/assets/2423189/25474348/923dc44e-2b3b-11e7-9445-73bae4d6530c.png)
![screenshot from 2017-04-27 11-10-40](https://cloud.githubusercontent.com/assets/2423189/25474349/93b27658-2b3b-11e7-894f-0df8904bc26c.png)
Mostly there's a problem of reverse order when locking and unlocking the screen. From center to aggregate menu, there is an extra issue.

**Comment by JasonLG1979** [comment]
Well at least they're all grouped together. We can't decide the order in which extensions load so we can't absolutely determine their order in the aggregate menu.

**Comment by cyberalex4life** [comment]
Well, with my mods, the order is restored

**Comment by JasonLG1979** [comment]
What version are you using? Because that branch I asked you to test doesn't have a default player.

**Comment by cyberalex4life** [comment]
The default branch, if you haven't merged the new one

**Comment by JasonLG1979** [comment]
I just merged that PR.

**Comment by cyberalex4life** [comment]
In fact there is only one small thing: if smplayer is started first and vlc afterwards, after locking and unlocking, vlc comes first. But default player position is always preserved.

**Comment by JasonLG1979** [comment]
> In fact there is only one small thing: if smplayer is started first and vlc afterwards, after locking and unlocking, vlc comes first. But default player position is always preserved, and all players are toghether.

That's a matter of which player is detected 1st on the MPRIS DBus interfaces. I don't think we can do anything about that.

**Comment by cyberalex4life** [comment]
Yeah, I agree, with that, to do that you should actually save last list, it would complicate far beyond reward.

**Comment by JasonLG1979** [comment]
> Yeah, I agree, with that, to do that you should actually save last list, it would complicate far beyond reward.

Pretty much. Another layer of complexity to an already stupid complex extension.

**Comment by JasonLG1979** [comment]
@cyberalex4life is this still an issue for you? Care to try the latest release and see what you think maybe sniff out some bugs for me?

**Comment by cyberalex4life** [comment]
In my tests I found out that in function `_addPlayerToMenu` `actualPos` should look like this:
`let actualPos = this.desiredMenuPosition + this.nbPlayers()-1; `

New opened players are still added under the one(s) already opened.

At comeback from screensaver players seem to be sorted alphabetically decending.

**Comment by JasonLG1979** [comment]
The grouping is the most important part at this point. As we've discussed coming back from sleep or what not is really out of our hands. From what I understand it effectively reloads the shell. We're at the mercy of the order in which they appear in DBus. I'll look into the starting point though.

**Comment by JasonLG1979** [comment]
I also need to look into a small bug where the padding of the panel text becomes to wide when the shell is reloaded.

**Comment by cyberalex4life** [comment]
Maybe you could try an alphabetically acending order.

**Comment by JasonLG1979** [comment]
I'm not against that.

**Comment by JasonLG1979** [comment]
I'm not against that as far as initial loading of existing players. I'm not so sure about resorting the player order every time a new player is added after that though. That could be a PITA

**Comment by JasonLG1979** [comment]
On a somewhat related note. We could improve how the manager decides which player is the active player by adding a timestamp to the status so that if 2 players have the same status the one with the most recent timestamp would be considered the active player. Right now it's just by status.

**Comment by JasonLG1979** [comment]
There @cyberalex4life I moved the starting point of the extension when in the system menu. Better?
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/2e80b8bef59c592c839e0eb90b120a8d7ee9a636

**Comment by cyberalex4life** [comment]
Yeah, about that, I've been testing the '-1' these days. There is really no rocket science about it. Sometimes things work well without it, then, at some reboot, position shifts. The starting point does not need moving, it's really where it should be. 

If I update the `desiredMenuPosition` in `_addPlayerToMenu` '-1' is definitely needed, at least in my GS configuration.

About sorting the players: I was thinking that, since we've already got some sorting order in dbus, why not reload the players every time a new player is opened or removed, then update the menu. This would solve the need to sort by ourselves each time, except it should be backwards.

**Comment by JasonLG1979** [comment]
> If I update the desiredMenuPosition in _addPlayerToMenu '-1' is definitely needed, at least in my GS configuration.

Kinda, I  desiredMenuPosition to be rfkil not rfkil +1 which should have the same effect.

**Comment by cyberalex4life** [comment]
no it's ok, like I said, I customize some extensions as I need to.

**Comment by JasonLG1979** [comment]
> About sorting the players: I was thinking that, since we've already got some sorting order in dbus, why not reload the players every time a new player is opened or removed, then update the menu. This would solve the need to sort by ourselves each time, except it should be backwards.

I want to be a good "Shell Citizen" part of that to me is doing as little UI trashing as possible. To me the order of the players coming back from the screensaver doesn't warrant destroying and rebuilding our whole UI everytime a new player is added or removed. I'm totally OK with sorting the players anyway you'd like initially because we have to create the UI anyway reordering them doesn't make that any more expensive.

**Comment by cyberalex4life** [comment]
It just seems a bit more sense, but I've seen that perfection with divergence or freedom in Linux means trouble in general. At some point I understood there's not much I can do about it. I had to work my way on my own. Perfection is subjective. At some point I understood why GS developers keep a low set of default extensions and don't add the ones that "should be included by default". In the end, this is actually the power of Gnome Shell, by empowering the user.

The problems that rise from distro to distro is usually what keeps me away from being a developer, or getting myself into a  low supported project, even one that I need.

**Comment by JasonLG1979** [comment]
I'm not trying to squash your freedom. If you can find a way to minimize UI updates and achieve your goal by all means put in a PR. I'm pretty sure you can just move things around in the menu without rebuilding them. To me it's not worth the added complexity and trouble of implementing you're more than welcome to hack around and see what you can come up with.

**Comment by cyberalex4life** [comment]
You're not squashing my freedom, the thing is that I may  do that to you and the  users of this extension,

**Comment by JasonLG1979** [comment]
> You're not squashing my freedom, the thing is that I may do that to you and the users of this extension,

OK cool. I got the impression that you thought I was coming off as some sort of gatekeeper trying to keep you from doing what you wanted.

I try my best to do what users want with this extension. That's why there are so many user options. If this where just for me I would hard code it the way I liked it and there would be no need for options.

Like I said if this is something you want to see added and it can be done reasonably efficiently put in a PR and it'll probably get added.

**Comment by cyberalex4life** [comment]
GS is build to be visually simple but powerfully configured in the back (like dconf). and this is something I respect about it, I care about this philosophy. Sometimes work and my way of doing things made me search for more features, sometimes i needed some pleasure to just keep working. 

I can agree that my system is overcrowded, it seems like GS is not made for this.

**Comment by cyberalex4life** [comment]
I generally disagree with extensions like `Put Windows `and 'Taskbar' that make GS more KDE-ish. But I have asked  for features on some extensions. I even encouraged developers to make different views possible because users tend to have different ways of doing things. But 'Taskbar' and 'Put Windows' are usually too much for me, and I don't use them.

**Comment by JasonLG1979** [comment]
I'm happy to have as many options as users want in this extension I just try to keep sane defaults. For me it's fun to open an app and flip switches and push buttons and see what they do,lol!!!

**Comment by cyberalex4life** [comment]
I like a small number (rather limited to say) of visual options for GS since it's made for simplicity. I do configure it a lot in dconf. I also like a unitary set of shortcuts cross-distro and even cross Visual Shells (DE's). KDE's is by far the most Windows-ish DE. It was hard for me to escape Windows in faculty, it mostly was a crusade. I wanted to escape cracks and torrents and all the illegal stuff, and I wanted to be free. KDE was bringing me closer to Windows, guess this is a psychological thing. I also knew that going Linux would help me a lot at some point (far-far away.. :)) ), and in the end turned into addiction.

**Comment by JasonLG1979** [comment]
> I wanted to escape cracks and torrents and all the illegal stuff,

That was one of the reasons I switched to Linux myself. It easier on my conscious.

**Comment by JasonLG1979** [comment]
@cyberalex4life you want to test https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/6feacadece6d3e3d8c75ea47943804f77e279ac9 It should Sort existing players alphabetically when the extension is enabled or any time the Shell is restarted.

**Comment by cyberalex4life** [comment]
On a few short runs, looks good.

**Comment by JasonLG1979** [comment]
I would still like add a timestamp to the status as a "tie breaker" to decide the active player. Currently the manager just looks for the 1st player with the highest status (play, pause, stop) so there's no way to break a tie if 2 players for example are paused and you restart the shell. The active player could end up not being the last player you interacted with. My thought is to save a json string of player names and timestamps that could be read and compared to existing players at initial start up.

**Comment by cyberalex4life** [comment]
Timestamps are more solid. What about sorting on timestamps?

**Comment by JasonLG1979** [comment]
> Timestamps are more solid. What about sorting on timestamps?

Not against it. It would insure the order stayed the same.

**Comment by cyberalex4life** [comment]
You would need too timestamps for each player, the opening and the activation.

**Comment by JasonLG1979** [comment]
We really don't even need timestamps. We could just save the array of player names and the active player name. Arrays keep their order.

**Comment by cyberalex4life** [comment]
More of a workaround. See that's what my thought is about in Linux, like the position. Working around the central mechanism, especially in vulnerable parts.

**Comment by JasonLG1979** [comment]
> More of a workaround. See that's what my thought is about in Linux, like the position. Working around the central mechanism, especially in vulnerable parts.

Well whatever you want. Roll up your sleeves, clone the repo and let's see what you can come up with. I think remembering the order of the players and the active player would be a great addition. Better get to work,lol!!!

**Comment by cyberalex4life** [comment]
yeah, I have too learn some mysql and php. It looks like I'm starting job from the 1st of Julie. I'll probably be testing websites initially, since it seems I like it and nobody else wants that. Then I have in plan to do some work one GS too.

I understand what you say. Everyone has a limited amount of energy, time and will. I'm actually breaking from learning now. We'll keep in touch about this.

**Comment by JasonLG1979** [comment]
@cyberalex4life I'm going to close this. It's kinda meandered a bit. I've opened a new issue so we can focus on the current state of things.

**Comment by cyberalex4life** [comment]
ok
