### ISSUE TITLE
Testing on HiDPI screens.

### ISSUE THREAD

**Issue by JasonLG1979** [JasonLG1979/gnome-shell-extensions-mediaplayer#386]
I've done the best I can as far as making sure the extension scales properly on HiDPI screens but I do not own a HiDPI monitor. It would be nice if someone with one of those fancy monitors would test out HiDPI support.

**Comment by MichaelMure** [comment]
This is what I get on a 13.3" QHD+ screen (3200 × 1800).

![ext](https://user-images.githubusercontent.com/294669/27513791-bc0677de-59ae-11e7-93b8-4aa7ba3050c9.png)

**Comment by MichaelMure** [comment]
It seems to grow the system menu horizontally for no reason. If I disable the extension, the menu is much more compact.

**Comment by JasonLG1979** [comment]
@MichaelMure Thank you so much for your help!!!

What are your values for the "Large cover size" and "Small cover size" settings?

**Comment by MichaelMure** [comment]
Default values, 128px and 48px.

**Comment by JasonLG1979** [comment]
What is your Scale Factor? And GNOME Shell version?

**Comment by MichaelMure** [comment]
Gnome shell version 3.22.2

> ✗ gsettings get org.gnome.desktop.interface scaling-factor
> uint32 2

**Comment by JasonLG1979** [comment]
Well I was trying to scale the menu to fit the large cover size setting. I'm not exactly sure why but that apparently doesn't work as I expected. I think I'll just do the reverse and remove the cover size settings and  try to make sure the large cover fits in the menu. we'll see how that works.

**Comment by JasonLG1979** [comment]
There's something screwy going on with the scaling of the system menu. You would expect that if the css says that the width of the menu is say 200px and the scale factor is 2 that the menu would actually be 400px. Not the case for some reason? So far in my measurements a scale factor of 2 actually means 1.5 and some change for the width of the system menu...

**Comment by JasonLG1979** [comment]
@MichaelMure can you test this release: https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/download/v0.2.4/mediaplayer.patapon.info.zip

**Comment by MichaelMure** [comment]
Is this a released version ? I can't find a way to see the installed version number, appart from metadata.json that say version 46...

If not, how do you install the zip ? I tried gnome-tweak-tool but it tell me that the zip is corrupted.

**Comment by JasonLG1979** [comment]
v46 is what the extension site calls it. They put their own version on it. v46 is out of date at this point. I uploaded a new version at the extension site like a week ago but it's waiting for approval.

What distro for install instructions?

**Comment by JasonLG1979** [comment]
Try this release. https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/tag/v0.2.5

I'm not sure why it's saying the zip is corrupted? They all seem to work for me?

**Comment by MichaelMure** [comment]
Debian

This time I get a "invalid extension" error ...

**Comment by JasonLG1979** [comment]
Weird? Anyway install instructions are here:
```sudo apt-get install git automake gnome-common gettext libglib2.0-dev git```
```git clone git clone https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer.git```
```cd gnome-shell-extensions-mediaplayer```
```./autogen.sh```
```make zip-file```

Install the zip file with GNOME Tweak Tool.

**Comment by MichaelMure** [comment]
.... and I get a "invalid extension" .... ¯\_(ツ)_/¯

**Comment by JasonLG1979** [comment]
Very strange? What version of Debian? I'll throw it in a VM.

**Comment by JasonLG1979** [comment]
Try putting "version": 50 in the metadata.json maybe Debian is looking for a version # for some reason?

**Comment by JasonLG1979** [comment]
Did you remove the old extension 1st? And did you restart the Shell after you installed it.

Generally I remove the extension. Close Tweak Tool. Restart the Shell. Reopen Tweak Tool. Install the new extension. And restart the Shell again. It will refuse to load a new version if one is already loaded.

**Comment by MichaelMure** [comment]
I'm using debian testing, but as I didn't update, it's the stable version since a few days.
There is no version number inside the zip, only once it's actually installed.
I tried the remove/restart/install with the same result.

That said, installing from https://extensions.gnome.org works just fine ...

**Comment by JasonLG1979** [comment]
@MichaelMure, sorry but I just tested a clean install of Debian 9 and I could not reproduce your install issues. Everything worked fine for me?

**Comment by MichaelMure** [comment]
@JasonLG1979 maybe i just have something broken on my machine ...

Please tell me when the new version get approved by gnome so I can show you how it looks

**Comment by JasonLG1979** [comment]
I will.

**Comment by JasonLG1979** [comment]
You could always just extract the zip and manually put it in ~/.local/share/gnome-shell/extensions?

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/download/v0.2.6.1/mediaplayer.patapon.info.zip

**Comment by mart-w** [comment]
On the current version, with HiDPI scaling set to 2, the cover art is displayed way too large when zoomed. Without scaling, it looks all right. The overall menu width seems to be the same with both scaling factors, by the way.

I’m running GNOME 3.18.5 on Ubuntu GNOME 16.04.2 with a display resolution of 2560 × 1440.

***Scaling factor: 1***
![bildschirmfoto von 2017-07-16 19-43-13](https://user-images.githubusercontent.com/5788421/28249947-944c97de-6a5f-11e7-819e-c946329d3546.png)

***Scaling factor: 2***
![bildschirmfoto von 2017-07-16 19-44-17](https://user-images.githubusercontent.com/5788421/28249948-94727486-6a5f-11e7-9c4d-66d3d6a5ee20.png)

**Comment by JasonLG1979** [comment]
Currently I don't do anything as far as scaling because I can't figure out how the Hell GNOME decides to scale what. As you said the menu doesn't appear to change total width much at all. Although the padding looks about twice as big. What does the small cover look like?

**Comment by JasonLG1979** [comment]
@mart-w you want to pull the latest git and let me know how that looks?

**Comment by mart-w** [comment]
That’s with a scaling factor of 2; looks all right to me. In the last version, only the zoomed version was too large with scaling, the small version looked fine.

Also, where did my German translation go? The commit seems to have vanished.

![bildschirmfoto von 2017-07-19 09-46-37](https://user-images.githubusercontent.com/5788421/28356130-308d55b2-6c67-11e7-82c5-9ec8f1cf5291.png)

**Comment by JasonLG1979** [comment]
> German translation go

Well shit I must have pushed to the repo without pulling from master 1st at some point. I'll fix it here in a sec. My bad, sorry about that. If you can't tell my workflow model can best be described as "Hamster on methamphetamine", lol!!!.

**Comment by JasonLG1979** [comment]
There @mart-w I think I did that right. I added your translations back.

**Comment by MichaelMure** [comment]
![sans titre](https://user-images.githubusercontent.com/294669/28408562-de4d1500-6d72-11e7-9f36-265b5fa1401c.png)

It looks like this with the latest version available on gnome-extension website. Much better :)

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
