### ISSUE TITLE
Translations need updating.

### ISSUE THREAD

**Issue by JasonLG1979** [JasonLG1979/gnome-shell-extensions-mediaplayer#387]
To all the awesome translators out their thanks!!! The extension has changed a lot recently and the translations could use updating.

**Comment by mart-w** [comment]
I updated the German translations, see #398.

**Comment by JasonLG1979** [comment]
Thanks!!!

**Comment by mart-w** [comment]
I just wanted to update the German translation for the new menu items but I ran into some trouble: One of the PO-Sourcefiles mentioned in po/POTFILES.in is src/org.gnome.shell.extensions.mediaplayer.gschema.xml.in, which doesn’t seem to exist. When I use src/org.gnome.shell.extensions.mediaplayer.gschema.xml instead and generate my POT, I get duplicates for the following translation strings:

- Always hide the indicator in the system menu
- Always keep the active player menu open
- Always show a Stop Button in the Player controls (that one even shows up three times)
- Display the currently playing song's rating on a 0 to 5 scale
- Show a Play Status Icon for each Player
- Show shuffle and repeat buttons

Is that a mistake on my end?

**Comment by JasonLG1979** [comment]
> I just wanted to add German translations for the new menu items but I ran into some trouble: One of the PO-Sourcefiles mentioned in po/POTFILES.in is src/org.gnome.shell.extensions.mediaplayer.gschema.xml.in, which doesn’t seem to exist. When I use src/org.gnome.shell.extensions.mediaplayer.gschema.xml instead and generate my POT, I get duplicates for the following translation strings:

Not your fault. gschema.xml.in doesn't exist since we moved to meson. I'll fix it.

**Comment by JasonLG1979** [comment]
Done

**Comment by mart-w** [comment]
What about the duplicate strings?

**Comment by JasonLG1979** [comment]
> What about the duplicate strings?

What do you mean?

**Comment by mart-w** [comment]
> When I […] generate my POT, I get duplicates for the following translation strings:
> 
> - Always hide the indicator in the system menu
> - Always keep the active player menu open
> - Always show a Stop Button in the Player controls (that one even shows up three times)
> - Display the currently playing song's rating on a 0 to 5 scale
> - Show a Play Status Icon for each Player
> - Show shuffle and repeat buttons

That’s what I see in Poedit once the PO template is regenerated from the files in POTFILES.in.
![bildschirmfoto von 2017-08-06 01-36-46](https://user-images.githubusercontent.com/5788421/28999457-cb1f8986-7a47-11e7-80f3-009c091be5a2.png)

**Comment by mart-w** [comment]
I just noticed that there are always subtle differences between the “duplicates”, e. g. different capitalisation or an additional full stop at the end. Maybe that’s what causes the problem – after all the POT is generated from the strings in the source code, from my understanding.

**Comment by mart-w** [comment]
Nevermind, my bad. In most cases you simply used the same strings for the summaries and descriptions of the options. I should pay more attention.

**Comment by JasonLG1979** [comment]
> you simply used similar strings for the summaries and descriptions

I never really understood the difference between summaries and descriptions they seem a bit redundant to me. Might just get rid of one or the other if they are not required.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
