### ISSUE TITLE
Make the manager smarter.

### ISSUE THREAD

**Issue by JasonLG1979** [JasonLG1979/gnome-shell-extensions-mediaplayer#388]
As discussed in https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/329

Currently the manager(you guessed it the class that manages the player menus) is not very smart. It doesn't remember the existing player order or the active player when the Shell is restarted. Currently if the Shell is restarted or the extension is restarted it just puts players in alphabetical order and sets the active player based on the 1st player it finds with the highest state.status (playing, paused, stopped) so when the shell restarts you might end up with the active player not actually being the last player you interacted with and the players may not be in the same order as they were.

I'd like for the manager to remember the player order and the last active player so that when the system returns from sleep/suspend/Shell restart/screensaver everything will be as it was before hand.

**Comment by ferdnyc** [comment]
Sounds like that could be done by keeping a state list in a dconf/gsettings key, yes? Something similar to `org.gnome.shell` keys like `enabled-extensions`, `favorite-apps`, `command-history`, or `looking-glass-history`.

**Comment by JasonLG1979** [comment]
> Sounds like that could be done by keeping a state list in a dconf/gsettings key, yes? Something similar to org.gnome.shell keys like enabled-extensions, favorite-apps, command-history, or looking-glass-history.

That was my plan. Then it's just a matter of a little array sorting Fu.

**Comment by JasonLG1979** [comment]
I figured I'd give someone else a shot to figure it out. If I don't get to it 1st. It's on my list of things to do but it really doesn't effect me because I generally don't have more than one media player open at a time and I don't use the screensaver or sleep and what not on my desktop.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
