### ISSUE TITLE
Broken in Fedora 24

### ISSUE THREAD

**Issue by doolittle42** [JasonLG1979/gnome-shell-extensions-mediaplayer#391]
This last update no longer shows the media player in the system menu (or anywhere else) until the media player is running.

 Is this a bug or 'feature'?

**Comment by JasonLG1979** [comment]
It's neither. see https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/390

**Comment by doolittle42** [comment]
OK, I just didn't check for closed issues.

**Comment by JasonLG1979** [comment]
You'll have that,lol...

**Comment by JasonLG1979** [comment]
@doolittle42 I added https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/CONTRIBUTING.md so that anyone in the future will be given an opportunity to go over the contributing guidelines before contributing.

**Comment by doolittle42** [comment]
Launching the media player was (one of) my favorite features. Without that, I no longer need this extension since Gnome has media controls in the top bar already.

**Comment by JasonLG1979** [comment]
> Launching the media player was (one of) my favorite features. Without that, I no longer need this extension since Gnome has media controls in the top bar already.

Ok

**Comment by doolittle42** [comment]
Please don't take that as an insult - I do appreciate all the work you put into this extension & I may try it again later. Thanks.

**Comment by JasonLG1979** [comment]
I didn't. I would have happily kept the feature if it wasn't buggy and redundant. I just got tired of fixing it.
