### ISSUE TITLE
latest version makes system menu thinner when the player is opened

### ISSUE THREAD

**Issue by davidbepo** [JasonLG1979/gnome-shell-extensions-mediaplayer#392]
screenshots:
![captura de pantalla de 2017-07-07 11-06-27](https://user-images.githubusercontent.com/18667173/27951228-734b2f80-6304-11e7-910d-9cc3aa59e3c7.png)
when the player is closed:
![captura de pantalla de 2017-07-07 11-06-31](https://user-images.githubusercontent.com/18667173/27951236-815fe3ea-6304-11e7-9411-8f3ab450f89f.png)

**Comment by JasonLG1979** [comment]
Yep, that has been fixed. You can build from the master branch or wait (what seem like a long time) for the latest version to be approved on the extensions site.

**Comment by JasonLG1979** [comment]
@davidbepo Here I just did a release. https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/download/v0.2.6.2/mediaplayer.patapon.info.zip

**Comment by davidbepo** [comment]
verified fixed thanks
