### ISSUE TITLE
SyntaxError in widget.js

### ISSUE THREAD

**Issue by wangxa** [JasonLG1979/gnome-shell-extensions-mediaplayer#393]
In the late git submission (dda86c5), I got:

```
JS ERROR: Exception in callback for signal: extension-found: SyntaxError: missing : after property id @ /usr/share/gnome-shell/extensions/mediaplayer@patapon.info/widget.js:952
```
The line 952 in widget.js defines a function:
```
_setPithosRating(rating) {
```
It should be:
```
_setPithosRating: function(rating) {
```

**Comment by JasonLG1979** [comment]
My bad, sorry about that. I don't know how or why I changed that? The funny thing is that it doesn't throw an error for me on Fedora 26/GNOME 3.24.

**Comment by wangxa** [comment]
Thank you for fixing it.
