### ISSUE TITLE
New Official Icon for Media Player Indicator

### ISSUE THREAD

**Issue by LinxGem33** [JasonLG1979/gnome-shell-extensions-mediaplayer#397]
hi @JasonLG1979 
##
i wanted to contribute and get a little bit more involved in your project so I’ve started by designing you  6 different new logo's for the project i have designed in both SVG and PNG formats the latter having varying sizes to to be used in different scenarios please see below the finished products just let me know which one you like or don’t like :smile: , if this is something which you think that would benefit your project i would be pleased to forward you all the project files for you to use as you wish.
##
||||
|-----|-----|-----|
|![media-player-indicator-logo](https://user-images.githubusercontent.com/19158615/28219663-a9a59c72-68b4-11e7-95ab-08e61dac6ffc.png)|![rect4279](https://user-images.githubusercontent.com/19158615/28219913-94923b1e-68b5-11e7-8a5e-801091dfcc4c.png)|![rect429](https://user-images.githubusercontent.com/19158615/28219926-9f33cc04-68b5-11e7-8832-d823e8949fa7.png)|

||||
|-----|-----|-----|
|![media-player-indicator-logo svg1](https://user-images.githubusercontent.com/19158615/28220251-b3ed3580-68b6-11e7-8e6d-c1f0a074106b.png)|![media-player-indicator-logo svg3](https://user-images.githubusercontent.com/19158615/28220265-be740ba0-68b6-11e7-8b4a-7ecb2f7012f3.png)|![media-player-indicator-logo svg5](https://user-images.githubusercontent.com/19158615/28220357-0975339a-68b7-11e7-8997-917ab4136934.png)|

##
kind regards - LinxGem33

**Comment by JasonLG1979** [comment]
Love the Design!!! Not so sold on the color palette. Maybe a little less pastel? Black, that red is alright and the blue is ok too, the yellow I'm on the fence with. I guess I'm just not digging that purple I guess,lol!!!

**Comment by LinxGem33** [comment]
@JasonLG1979 
lol... just give me your colour specs and ill redesign :smile:

**Comment by JasonLG1979** [comment]
I'm a fairly good designer myself. I designed the Pithos logo. hit me with the SVG of what you got and I'll show you what I mean.

**Comment by LinxGem33** [comment]
[media-player-indicator-logo.svg.zip](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/files/1149047/media-player-indicator-logo.svg.zip)

**Comment by JasonLG1979** [comment]
I don't know? This is kinda what I'm talking about.
![media-player-indicator-logo](https://user-images.githubusercontent.com/6667703/28229586-f12aade6-68a8-11e7-846c-9b0bf69e8c44.png)

You want to pixel fit it. And you want to make sure it transfers to a symbolic Icon.

**Comment by JasonLG1979** [comment]
If I can I'd like to use the logo's symbolic icon as our default fallback icon instead of the generic audio mimetype icon in the panel.

**Comment by JasonLG1979** [comment]
I've played with designing a new Icon myself a bit and I can't come up with anything much better then the current icon. I think you're on the right track though. As far as style inspiration I'd say look at the stock GNOME icons. i'd like the icon to not look out of place along side them.

**Comment by LinxGem33** [comment]
@JasonLG1979 

ive reworked the design and adapted your clour scheme let me know what you think :smile: 
##

![media-player-indicator-logo svg](https://user-images.githubusercontent.com/19158615/28231195-1c68e034-68e2-11e7-94c2-8d9fbc12862c.png)

**Comment by JasonLG1979** [comment]
How about something like this? It's basically a tweaked version of the audio-headphones icon from the numix icon set.
![audio-headphones](https://user-images.githubusercontent.com/6667703/28239655-0231f6a6-6937-11e7-9a11-86e158daa952.png)

**Comment by JasonLG1979** [comment]
I like your symbolic icons though. My only problem with them is that symbolic icons are generally used at 16x16px and that sound wave line would get lost in a blur at that size.

**Comment by LinxGem33** [comment]
@JasonLG1979 

that icon looks nice, i agree with your point regarding the symbolic icon but maybe  a thicker stroke could compensate.

**Comment by JasonLG1979** [comment]
> that icon looks nice

The credit goes to whoever originally designed the headphones icon. I basically just did the equivalent of color in a coloring book,lol!!!

 

> i agree with your point regarding the symbolic icon but maybe a thicker stroke for the sound wave could compensate.

I'd have to see the SVG at 16x16px. I think I prefer the one with the open ear pieces.

**Comment by JasonLG1979** [comment]
The only other stipulation is that you release what ever icon you make under this licence:
 https://creativecommons.org/licenses/by-sa/4.0/

**Comment by LinxGem33** [comment]
@JasonLG1979 
apologies for the late reply, please see below example of the symbolic icons at 17px x17px but they look the same at 16px also i included the raw files if you want to adjust them and it shouldn’t be a problem releasing them under a CC BY 4.0 license.
##
![wmpi](https://user-images.githubusercontent.com/19158615/28342157-d2dfa846-6c0e-11e7-9d82-79e1be3bac62.png)

![bmpi](https://user-images.githubusercontent.com/19158615/28342163-db81599a-6c0e-11e7-8c6b-8efd4b91dae7.png)
##

**Comment by ferdnyc** [comment]
I just wanted to jump in and say that the higher (and lower) peak on the sound wave in those last symbolic icons makes _all_ the difference. It keeps the reduced-size icon from looking like... well... like a doorway, or a tunnel, which is pretty much what the previous version looked like when I manually zoomed them down to 16-ish pixel sizes.

**Comment by JasonLG1979** [comment]
@LinxGem33 I borrowed a liberal amount of code from your Extension and adapted it to make my own tabbed prefs dialog and now I have a proper place to display your logo you still interested?

![screenshot from 2017-08-06 20-53-10](https://user-images.githubusercontent.com/6667703/29009742-872b283a-7aeb-11e7-8ae1-0540ccee10d2.png)

**Comment by LinxGem33** [comment]
@JasonLG1979 
yeah sure just let me know what you need in regards to the icon etc, regarding the prefs.js its looking really good, @lexruee has been instrumental in the design of our prefs.js settings widget for Arc menu, i think its good that if we can get some of the third party gnome developers together working on each others projects in whatever way we can, so in short am all for getting involved and helping out in which ever way i can :+1:  ( now if we can just get the world to do the same thing :smile: )

kind regards

**Comment by JasonLG1979** [comment]
@LinxGem33 Thanks. @lexruee was the driving force in the update. I'm all about sharing code and knowledge. We kinda got to being as there are no docs to speak of as far as Extension development. I'm constantly reading OP's source code to see how they're doing things.

One thing that really needs to change is the St widgets, they just suck,lol!!! I bet 1/2 the code in my extension is widget sub-classes. I fight them all the way. And then you got stupid shit where you can't put this widget in that container and so in. It's to the point where I'll sub class something just so it will pass the "isInstance" test and the wipe out the widget and build my own...

**Comment by JasonLG1979** [comment]
As far as Icons really what I need is a 16px and 48px svg symbolic icon. I don't think I really need a full color icon. I like this: https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/397#issuecomment-316214296

**Comment by JasonLG1979** [comment]
I'll use the 16px for the panel and the 48px for the about dialog page and the extension site. I haven't decided if I want to keep using the generic icon for the fallback cover or not?

**Comment by LinxGem33** [comment]
regarding the lack of documentation i totally know what you mean ive been reading up this weekend in preparation for new features i want to add for Arc menu v15.

regarding the icons symbolic leave it with me and ill create the specified sizes of the originals and also see about creating a tweaked alternative version of the originals once finished ill leave a link to the source files with the sizes etc.

kind regards

**Comment by JasonLG1979** [comment]
Thanks!!!

**Comment by JasonLG1979** [comment]
If you don't mind me asking what are the new features?

**Comment by LinxGem33** [comment]
@JasonLG1979 

please see below new re-designed symbolic icons all the icons have been tested and have better readability in the panel due to the new designs i decided to improve the designs and create new symbolic icons so you can pick which one you like i have done them in SVG and PNG formats at the specified sizes (**16px & 48px**) it took me a little while but they are all original ready specifically for your project :+1: 
##
|||||||||
|-----|------|-----|-----|-----|-----|-----|-----|
|![mpi348-symbolic](https://user-images.githubusercontent.com/19158615/29013978-7e2011f8-7b3e-11e7-83b3-40afaf5b8c47.png)|![mpi48-symbolic](https://user-images.githubusercontent.com/19158615/29013991-924b3108-7b3e-11e7-963a-dcac4b488f1a.png)|![mpi548-symbolic](https://user-images.githubusercontent.com/19158615/29013998-9e5305de-7b3e-11e7-9d66-c20bae7c769a.png)|![mpi748-symbolic](https://user-images.githubusercontent.com/19158615/29014017-b7cff10c-7b3e-11e7-9b1e-776ca6572efb.png)|![mpi948-symbolic](https://user-images.githubusercontent.com/19158615/29014061-148ea424-7b3f-11e7-9320-45a139d36e91.png)|![mpi1048-symbolic](https://user-images.githubusercontent.com/19158615/29014101-3cc89ad0-7b3f-11e7-9dcc-a43a2a40c44f.png)|![mpi1148-symbolic](https://user-images.githubusercontent.com/19158615/29014114-48a973d8-7b3f-11e7-9447-97e661961260.png)|![mpi1348-symbolic](https://user-images.githubusercontent.com/19158615/29014119-5649993c-7b3f-11e7-9484-a3dd8e8205b5.png)
##
please see below the zip file link containing all the raw files for your project just rename them to what you want.
##
[media-player-indicator-symbolic-icons.zip](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/files/1203989/media-player-indicator-symbolic-icons.zip)
##
kind regards

**Comment by LinxGem33** [comment]
@JasonLG1979 

regarding the new features im working on please see below its easier to illustrate
##
 the features are below ive done the UI for the settings, the logic still has to be implemented its just a rough start to the AZ feature and also the recent apps and also a couple of others etc suggestions for the logic are welcome as i start to develop this feature further, this illustration below is just for documentation and prototyping purposes .
##

![go5](https://user-images.githubusercontent.com/19158615/28996852-7cece0e4-79ff-11e7-9115-1b79aad08312.gif)

**Comment by JasonLG1979** [comment]
Disabling suspend is easy. just look at the caffeine extension.

**Comment by JasonLG1979** [comment]
> please see below new re-designed symbolic icons

I like the 3rd one best. They all look great though thanks!!!

**Comment by LinxGem33** [comment]
@JasonLG1979 

appreciate that ill take a look at the code for caffeine, i have uploaded a zip file link to all the raw files etc have fun, also you can release them under any licence you choose as they are all bespoke icons specifically for your project.

kind regards

**Comment by JasonLG1979** [comment]
@LinxGem33 thanks I'll get right on it.

**Comment by JasonLG1979** [comment]
I guess this closes this issue ;)

**Comment by JasonLG1979** [comment]
@LinxGem33 I decided to use the one with the lightning bolt it seemed to scale the best to me. I also pixel fit the icon. When designing icons, especially symbolic icons, you want to design in a grid so when the system displays the icon they look nice and sharp.

![screenshot from 2017-08-07 14-22-25](https://user-images.githubusercontent.com/6667703/29042415-718e9598-7b7c-11e7-8034-b915ebd6b700.png)

**Comment by JasonLG1979** [comment]
![screenshot from 2017-08-07 14-28-11](https://user-images.githubusercontent.com/6667703/29042511-c864052e-7b7c-11e7-8e21-c80fe1dc47ce.png)

**Comment by JasonLG1979** [comment]
@LinxGem33 What's your last name? Your github profile lists you as Andy C. I want to give  you an artwork credit.

**Comment by LinxGem33** [comment]
@JasonLG1979 

it looks really nice and sharp, yeah will defo use a grid in future for icons i should have in the first place, regarding the artwork credit you can leave at "Andrew C" or Andy C or even LinxGem33 that’s fine by me and i really appreciate it thank you. 

kind regards

**Comment by JasonLG1979** [comment]
LinxGem33 is it then.

**Comment by JasonLG1979** [comment]
Done.
