### ISSUE TITLE
Missing Stop button for mpDris player

### ISSUE THREAD

**Issue by roizcorp** [JasonLG1979/gnome-shell-extensions-mediaplayer#399]
I updated just now to 2.7.2

my extension is mainly used for controling MPD via mpDris2,

suddenly I cannot see the Stop button which served me in older versions, I tried to look in gsettings and the extensions configuration in gnome-tweak but couldn't identify such a setting to enable

**Comment by JasonLG1979** [comment]
It's been removed because 99.9% of the players don't even have stop in their UI's anymore. There's really no advantage to stop over pause with digital media, so it was removed because most of the time it just sat there unused taking up space.

**Comment by JasonLG1979** [comment]
I can add it back in as a user option for those that want a stop button.

**Comment by JasonLG1979** [comment]
This work for you? like I said a user option to show the stop button or not.

https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/e7d3d2fd347dcdfcb30f986624171c9c6ea3e81d

**Comment by roizcorp** [comment]
an option would be perfect - thanks!

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/tag/2.7.4

**Comment by roizcorp** [comment]
hi,

I'm probably doing something wrong, but I cannot see this option in the menu, the extension installed via extensions.gnome.org as the latest of today 
(I have difficulty to understand from the indicator's UI which version I currently have)

**Comment by JasonLG1979** [comment]
That version is a couple behind because it takes them f o r e v e r to approve a new release when I upload it.

**Comment by roizcorp** [comment]
damn...so no easy way to get notification about extension updates, uh?

**Comment by JasonLG1979** [comment]
They eventually get to you.
