### ISSUE TITLE
Hide generic primary indicator or fully hide player symbolic icon

### ISSUE THREAD

**Issue by zgwerby** [JasonLG1979/gnome-shell-extensions-mediaplayer#403]
Can you do option to hide primary indicator with generic "audio-x-symbolic" or fully hide player symbolic icon? Only show status indicator.

**Comment by JasonLG1979** [comment]
So you want just the status icon? (Play, Pause, Stop) I think without another icon (preferably the players symbolic icon) just the status icon would lack context.

**Comment by zgwerby** [comment]
Yes. Only playing status. Context? I think it was only optional feature. And players context you can see in system drop-down menu, can't see? Sorry for my poor english.

**Comment by JasonLG1979** [comment]
What I mean by context is that without the player icon the status icons lack meaning

**Comment by zgwerby** [comment]
Ок, but what to do with video players? Generic "audio-icon" in MPRIS2-compatible videoplayers сonversely help lack context. What I played now: totem or gnome-mpv or pure mpv? If don't work icon autoswitch, why I can't hide this ugly, non-informative symbol in extention options?

![2017-07-29 12-08-29](https://user-images.githubusercontent.com/21217444/28743841-f3b70718-7464-11e7-85c3-cfdf9e6da908.png)
![2017-07-29 12-09-14](https://user-images.githubusercontent.com/21217444/28743840-f3b529b6-7464-11e7-90af-25f32864d173.png)
![2017-07-29 12-09-51](https://user-images.githubusercontent.com/21217444/28743839-f3b3d5b6-7464-11e7-9a6e-97fcfc828edb.png)
![2017-07-29 12-11-15](https://user-images.githubusercontent.com/21217444/28743838-f3a3f75e-7464-11e7-88c8-1717431918d2.png)

**Comment by JasonLG1979** [comment]
> Ок, but what to do with video players?

I really don't see the point of a media player even putting up a MPRIS interface when it's playing a video. It's not like you're going to "watch" a movie with the media player minimized... You may want to file a bug with the player about that. I really have no good way of programmatically being to tell if the media in question is a video that works for every media player.

> totem or gnome-mpv or pure mpv or at all havent symbolic icon audacious? If don't work icon autoswitch, why I can't hide this ugly, non-informative symbol in extention options?

Not my fault. If they had a symbolic icon and followed symbolic icon naming convention it would show up.

**Comment by zgwerby** [comment]
Ok.

**Comment by JasonLG1979** [comment]
I'll look into ways to detect if the media is a video and just not show the extension at all if so.

**Comment by zgwerby** [comment]
Ok, thanx

**Comment by JasonLG1979** [comment]
@zgwerby I can't find a way to detect if it's a video that works across players. My advice is just disable mpris in the video players in question if you don't want them to show up in the extension.

**Comment by beanaroo** [comment]
I'd also like to hide the extra icon if possible. Player's symbolic icon is enough to know it is active and the menu provides context on playing status along with progress and controls etc.

**Comment by JasonLG1979** [comment]
> I'd also like to hide the extra icon if possible. Player's symbolic icon is enough to know it is active and the menu provides context on playing status along with progress and controls etc.

@beanaroo, this bug report is about hiding the primary icon. I assume you're talking about the play state icon. That's a reasonable request. I'll add a setting for that in the next release.

**Comment by lexruee** [comment]
@JasonLG1979 
I think I deserve a new release :-), hehe.
See pull-request: #427

Cheers,
Alex

**Comment by JasonLG1979** [comment]
Well there you go @beanaroo thanks to @lexruee https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/d96240eb205e745fbfef4d432b056883c15d30f9 add the ability to hide the secondary icon.

**Comment by JasonLG1979** [comment]
I'll do a new release here in a bit. Thanks again @lexruee !!!

**Comment by JasonLG1979** [comment]
There, https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/e139223f79acd5989802218776cdda8668b51ee8 now we're ready for a new release :)

**Comment by beanaroo** [comment]
Fantastic! Thank you, @JasonLG1979 and thank you @lexruee!!! I'm learning from your PR and hope to return the favor some day.

**Comment by JasonLG1979** [comment]
> I'm learning from your PR and hope to return the favor some day.

I may be a terrible example. I'm pretty new to js, although I'm pretty familiar with GObject stuff,lol!!!

**Comment by JasonLG1979** [comment]
The new release is up here on github https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/releases/tag/3.3 and has been pushed to the Extension site. It should show up there when it gets approved.
