### ISSUE TITLE
Missing launcher for rhythmbox in system menu

### ISSUE THREAD

**Issue by vladimirdarak** [JasonLG1979/gnome-shell-extensions-mediaplayer#406]
In previous version was possible to start rhythmbox from system menu when it is not running. Now the option is missing in system menu so it is not possible to start rhytmbox via this extension.

![media-indicator-bug](https://user-images.githubusercontent.com/4071399/28906121-a61d5c5a-7815-11e7-8f75-86f261175bd4.png)

I don't know if this is the bug or feature but for me was previous behavior better then current

**Comment by JasonLG1979** [comment]
Duplicate of https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/issues/367
