### ISSUE TITLE
The build script is impossible to install the extension to /usr/share

### ISSUE THREAD

**Issue by wangxa** [JasonLG1979/gnome-shell-extensions-mediaplayer#407]
The current `build` only install the extension to a user's home directory. The extension cannot be installed to `/usr/share` using this script. Although we can manually copy the files to the proper directories and run the post commands, it is really unconvenient.

**Comment by JasonLG1979** [comment]
That was done on purpose. You can still install system wide manually by running the ninja commands.
```
$ meson builddir --prefix=/usr
# sudo ninja -C builddir install
```

But system wide installs are not supported.

**Comment by JasonLG1979** [comment]
To elaborate system wide installs are not supported because we don't provide an easy way to unistall system wide installs(and never will). IMHO Extensions are meant to be installed on a user by user basis.

**Comment by wangxa** [comment]
```bash
$ meson builddir --prefix=/usr
# sudo ninja -C builddir install
```

Yes, I have tried this. But the problem of these statements is when you build a package in Fedora, the building script will try to install every thing to `/usr/`, instead of `${RPM_BUILD_ROOT}/usr`. Maybe, you know that the building script is run by a non-root user and `${RPM_BUILD_ROOT}` is defined as `/home/some_user/rpmbuild/BUILDROOT/package_name`. The building process is executed under the user's privileges not root's prilivege. So the building process will fail because the normal user cannot write to `/usr`.

**Comment by JasonLG1979** [comment]
Again system wide installs are not supported. You'll have to figure this one out for yourself.

**Comment by wangxa** [comment]
Thank you. I know it now.
