### ISSUE TITLE
The option dialog is too long to display on some size of screen

### ISSUE THREAD

**Issue by wangxa** [JasonLG1979/gnome-shell-extensions-mediaplayer#408]
My display is 1600x900 (16:9). Please see the screenshot. The extension option dialog cannot be fully displayed. The resize function of the dialog does not work.

By the way, the extension will crash gnome-shell (Fedora 26) occasionally and randomly.  

![screenshot from 2017-08-05 15-24-49](https://user-images.githubusercontent.com/1250269/28996189-e752453a-79f2-11e7-8a5b-fadc320b438c.png)

The full view of option dialog:

![screenshot from 2017-08-05 15-31-28](https://user-images.githubusercontent.com/1250269/28996204-3c14956e-79f3-11e7-8722-2c02cd46d522.png)

**Comment by JasonLG1979** [comment]
I know I'm actually working on that right now. I'm in the process of deciding if I want to break the settings up into tabs or just make the whole settings window scrollable?

**Comment by JasonLG1979** [comment]
> By the way, the extension will crash gnome-shell (Fedora 26) occasionally and randomly.

I run Fedora 26 and I don't have that problem. What player?

**Comment by wangxa** [comment]
To be honest, I am not so sure because gnome-shell just crashes one or two times a day. The system log shows nothing useful to say where the problem is. I think this is caused by some extensions. I have investigated openweather. This Thursday, I disabled mediaplayer, and there is crash. Today, I just updated the mediaplayer extension to the latest version. After enabling the extension, the crash came again. So I think this may be associated with this extension. But I am not sure.

Thank you.

**Comment by wangxa** [comment]
The players I used are Audacious, VLC, and Rhythmbox.

**Comment by JasonLG1979** [comment]
If the crash was caused by the extension it would be in the logs.

**Comment by JasonLG1979** [comment]
Well anyway would you open a new bug for that and I'll see if I can help track that down.

This commit closes this issue: https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/984f398b0622768257c28ba28c22416bdfa4f291
