### ISSUE TITLE
Translations do not show up

### ISSUE THREAD

**Issue by mart-w** [JasonLG1979/gnome-shell-extensions-mediaplayer#412]
When I wanted to “test-fit” my updated German translation and built the extension, I noticed that the translation files apparently don’t get loaded correctly; the interface was still in English. I tried to manually copy  `~/.local/share/locale` into `~/.local/share/gnome-shell/extensions/mediaplayer@patapon.info`, [as the GNOME extension FAQ suggests having the locale directory inside the extension directory itself](https://wiki.gnome.org/Projects/GnomeShell/Extensions/FAQ/CreatingExtensions), and had partial success: The tab titles and the about page added in commit c9c60c5fc0930f3a697359f2829e617918ca593e showed up in German, the rest still did not.
![bildschirmfoto von 2017-08-06 16-52-44](https://user-images.githubusercontent.com/5788421/29004464-bc47e1d0-7ac7-11e7-8053-ab151df7a383.png)

**Comment by JasonLG1979** [comment]
OK I think I fixed it. Let me know if that did the trick?

**Comment by mart-w** [comment]
Sadly no. Still exactly the same behaviour.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
