### ISSUE TITLE
Shrunken display elements in system menu

### ISSUE THREAD

**Issue by ferdnyc** [JasonLG1979/gnome-shell-extensions-mediaplayer#413]
Over on e.g.o user Hilyx writes to note that in recent releases, "The Cover Art isn't resizable anymore - the media keys are too small".

@JasonLG1979 explains:
> you can thank GNOME Shell's lackluster HiDPI support for that. I'll save you the details but basically UI elements currently don't scale in a consistent way . So for now the buttons inherit from a stock class and the cover images are static sizes that work on both HiDPI and normal screens.

Understandable, but at the same time the player controls, at least, _are_ rather uncomfortably small. (Especially for all of Gnome Shell's touch-input users, who I'm assured really do exist.) So it's still an issue, and I thought I'd log it more formally over here.

**Comment by ferdnyc** [comment]
Spitballing solutions, would it work out better for scaling (for that matter, would it even be possible?) if the player controls weren't just their icons, but larger active areas which contained the icons? I'm thinking something like the Shell's own system menu buttons, and perhaps even leveraging some of their code to handle scaling (which they must have handled, in some fashion) as well as for visual consistency.

So, perhaps instead of this:
![mediaplayerextension-currentlayout](https://user-images.githubusercontent.com/538020/29013349-81090be6-7b10-11e7-8cf1-477f16bf6494.png)

Maybe something along the lines of this:
![mediaplayerextension-largercontrolsmockup](https://user-images.githubusercontent.com/538020/29013363-91d2ea78-7b10-11e7-84f6-f4dbf4a600f3.png)

(But with the icons actually centered properly in the buttons, since I now notice that they're just _sliiightly_ off in my mockup.)

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/b4ba81ce225f8627bc93eddb2435981b83299d7c this commit a added the ability to resize the player icons. give the latest git a try it's more geared to HiDPI screens so they're kinda big. Otherwise I can ad an option to use the circle style buttons.

**Comment by JasonLG1979** [comment]
I could call the sizes small, medium, large and Holly Shit!!! LMFAO!!!!

**Comment by ferdnyc** [comment]
Or, for the discerning* Gnome Shell user, a choice of Large, Venti, or Grande buttons.

* – (read: pretentious)

**Comment by JasonLG1979** [comment]
for sure. lol!!!

**Comment by JasonLG1979** [comment]
Maybe I'll just change the setting name in the UI to "Button Style" and do small, medium, large and circular?

**Comment by JasonLG1979** [comment]
![screenshot from 2017-08-07 01-43-01](https://user-images.githubusercontent.com/6667703/29015031-c6e72df4-7b11-11e7-9131-455115b8ce5a.png)

**Comment by JasonLG1979** [comment]
Better. There's now an option to get the old style buttons back if you want.

**Comment by JasonLG1979** [comment]
> and perhaps even leveraging some of their code to handle scaling (which they must have handled, in some fashion) as well as for visual consistency.

The problem is that Some things are in px's and somethings are in em's and they don't scale the same. Add to that GIcons which basically scale themselves.

**Comment by ferdnyc** [comment]
Grr, I forgot GitHub did that. :-) Sorry, I was just using this report to illustrate a point about Gnome's HiDPI support, nothing actually-related over there.

**Comment by JasonLG1979** [comment]
No problem. They are after all related to the same, what I would consider upstream bug.
