### ISSUE TITLE
Player button style works partially  after recent commit

### ISSUE THREAD

**Issue by dasnoopy** [JasonLG1979/gnome-shell-extensions-mediaplayer#414]
...noticed this affter recent commit https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/d83eabc3917ad1713120e6839d43b22ec58b70e7 

- choosing MIN or MEDIUM style  : always  large buttons are displayed;
- LARGE  style  is supposed works as expected;
- CIRCULAR sytle  works fine. 

e.g. with small buttons : 
![screenshot from 2017-08-07 20-21-08](https://user-images.githubusercontent.com/296922/29056206-92ecdec2-7c01-11e7-8078-695bae597f22.png)

extension compiled from git-master  on Gnome 3.24.2 / default Adwaita themes / Audacious 3.8.2 / Archlinux 64bit

thanks

**Comment by JasonLG1979** [comment]
I know. I'll fix it here in a bit.
