### ISSUE TITLE
Media player extension changes to next track when I touch the seek bar

### ISSUE THREAD

**Issue by glaubersm** [JasonLG1979/gnome-shell-extensions-mediaplayer#417]
Hi
I use Quod Libet player on Gnome 3.24.2 Wayland session running on a laptop with touch screen and I has the problem that my summary describes.
The problem does not happen when I run Gnome under X11 instead Wayland.
Thanks.

**Comment by JasonLG1979** [comment]
I do not own a touchscreen (and have never used GNOME on a touchscreen) so I have no way to confirm or test possible solutions for your issue. If I had to guess it's probably an issue with touch in Wayland, as you said there is no issue in X. Do you have any problems with any other sliders in GNOME?

**Comment by glaubersm** [comment]
No problem with any other slider.
I just noticed that the same problem happens with VLC 2.2.6.

GTK inspector has a touch screen simulator, maybe it can help you.

**Comment by JasonLG1979** [comment]
I will have to look at Quod Libet's mpris code but according to spec if the seek position is invalid it's suppose to be ignored. My 1st thought was that the slider was returning an invalid value. My next thought is that maybe you should change the button style setting to use larger button. Maybe you're hitting the next button inadvertently?

**Comment by glaubersm** [comment]
Yes, I use larger buttons. However the problem does not happen with Clementine, so I'm not hitting the next button inadvertently.

**Comment by JasonLG1979** [comment]
So you don't have the same issue with the extension with Clementine?

**Comment by glaubersm** [comment]
No.

**Comment by JasonLG1979** [comment]
Then it's clearly not a bug in the media extension. I'll look at Quod Libet's mpris code.

**Comment by JasonLG1979** [comment]
Here is the method responsible for seeking in Quod Libet's mpris code:

https://github.com/quodlibet/quodlibet/blob/cbf5289be80fd85984ec2d8acb59c7ce6e62eee5/quodlibet/quodlibet/ext/events/mpris/mpris2.py#L200-L203

That method doesn't check the validity of the position given, and at a glance I do not know if ```player.seek``` preforms any checks either?

**Comment by JasonLG1979** [comment]
The best I could do would be to clamp the position sent to the method to always be in range of the track length but that really wouldn't help any though. Seeking to the very end of a song is pretty much the same as skipping to the next song.

**Comment by JasonLG1979** [comment]
> GTK inspector has a touch screen simulator, maybe it can help you.

I've played with GTK inspector for regular app debugging but I'm not sure if it works for Shell Extensions. I think Looking Glass would be the equivalent for Extensions and I'm unaware of any way to simulate touch in Looking Glass? I generally just use logging for debugging.
