### ISSUE TITLE
Doesn't work with "Extend Panel Menu" extension

### ISSUE THREAD

**Issue by fcastilloec** [JasonLG1979/gnome-shell-extensions-mediaplayer#418]
I love using the [Extend Panel Menu](https://github.com/julio641742/extend-panel-menu) extension but it doesn't seem to work with this extension at all. When Julio's extension is enabled, I can only use the default Gnome Media Player.
I'm not sure which extension is causing this problem but I've also filed issue [extend-panel-menu#52](https://github.com/julio641742/extend-panel-menu/issues/52) at their project.

**Comment by JasonLG1979** [comment]
I'll try it out and take a look at the code to see if I can see what the problem is.

**Comment by JasonLG1979** [comment]
After a brief test it appears the the extension basically hides/wipes out the panel items and recreates them as separate indicators, so you'd need to set the mediaplayer extension to either the right or center position.

**Comment by fcastilloec** [comment]
Thanks!!! I guess that it's up to Julio's extension to "recreate" your extension inside the volume one so it's neatly integrated.

**Comment by JasonLG1979** [comment]
That would be the logical place to put it but that may not be possible. One extension having knowledge of another is not an easy thing. It's probably just easier to not have the position set to system menu...
