### ISSUE TITLE
Auto Expand a Player if is the only one

### ISSUE THREAD

**Issue by roizcorp** [JasonLG1979/gnome-shell-extensions-mediaplayer#421]
it makes no sense that I have to click twice in order to get to the control buttons. The first one is clicking on the media player indicator (not part of system menu), the second is to select the only player in the list (in order to expand it) and only then I have access to the control button

I think the better solution would be that if only single player is active then automatically expand it

**Comment by JasonLG1979** [comment]
The current Active Player menu is already always open by default unless you turned off the option to always have the Active Player menu open. If only one player is in the menu it's the Active Player always.
