### ISSUE TITLE
Doesn't working and crashes after start

### ISSUE THREAD

**Issue by DolphinStKom** [JasonLG1979/gnome-shell-extensions-mediaplayer#422]
after compile and install, when start application

```
GLib.FileError: Не удалось открыть файл «/usr/share/gnome-shell/extensions/mediaplayer@patapon.info/schemas/gschemas.compiled»: сбой в функции open(): No such file or directory

Stack trace:
  getSettings@/usr/share/gnome-shell/extensions/mediaplayer@patapon.info/lib.js:27:24
  @/usr/share/gnome-shell/extensions/mediaplayer@patapon.info/prefs.js:31:19
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:49
```

**Comment by DolphinStKom** [comment]
My ebuild

[gnome-shell-extensions-mediaplayer-9999.ebuild.txt](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/files/1317666/gnome-shell-extensions-mediaplayer-9999.ebuild.txt)

**Comment by JasonLG1979** [comment]
I don't know much of anything about Gentoo. My guess is you're missing the package that compiles the gschema? Compiling from source is really only useful for devs. If you plan on contributing code awesome!!! Otherwise if you just want to use the extension then the best way to get it is from the extensions site.

**Comment by DolphinStKom** [comment]
I could not figure out the problem ... I can not understand why meson does not pick up the script meson_post_install.py

Temporarily decided to install an extension from the site, but it crumbles and loads the gnome and dbus process while artifacts
![123](https://user-images.githubusercontent.com/4992884/31298333-5f54983c-aaf2-11e7-908d-36d788eba0aa.png)

**Comment by JasonLG1979** [comment]
After looking closer I think I see the problem. Our meson build scripts do not support system wide installs.

**Comment by JasonLG1979** [comment]
System wide installs are possible but you'd need to modify the scripts. The reason that system wide installs are not supported is because 1. There is no real distro agnostic clean way to uninstall. 2. From a philosophical standpoint extensions are meant to be installed on a per user basis.

**Comment by DolphinStKom** [comment]
How to fix it? I just tried everything on my part, everything is installed without errors, all the files are correctly stored in the directory, but the schema file is not generated. I saw this operation in the script meson_post_install.py

one of the reasons why I do this is through ebuilds - I can at least interactively interact with content and do not install unnecessary, for example all locales and this is the philosophy of Gentoo))

**Comment by DolphinStKom** [comment]
In any case, I'm waiting for a response from eonpatapon regarding the mpDris2
https://github.com/eonpatapon/mpDris2/issues/98
because at the moment it's all hopelessly broken even if it's an extension with boxes

**Comment by JasonLG1979** [comment]
Like I said you'll have to modify the build script to install system wide. you'll have to figure that out yourself. System wide installs are not supported.
