### ISSUE TITLE
Placing the indicator on the left side of the top bar

### ISSUE THREAD

**Issue by fbruetting** [JasonLG1979/gnome-shell-extensions-mediaplayer#423]
Please support positioning on the left side, too! Taskwhisperer does this for example, maybe you can steal the code part from there. ;)

**Comment by JasonLG1979** [comment]
Sounds reasonable. I'll add it to the next release.

**Comment by lexruee** [comment]
@JasonLG1979 @fbruetting 
I quickly implemented this feature. I assume it's okay that the indicator is always on the right of any menu launcher or activities button.

Here is how it looks when using Arc-Menu.
![screenshot from 2017-10-08 23-45-48](https://user-images.githubusercontent.com/649340/31321304-23b16bd2-ac84-11e7-868f-d0f52c11b73f.png)

It also works with the default activities button:
![screenshot from 2017-10-08 23-46-03](https://user-images.githubusercontent.com/649340/31321250-21dfc9b2-ac83-11e7-8945-75323ea34832.png)

Lastly, I also tested it with the GNOME apps-menu:
![screenshot from 2017-10-08 23-45-29](https://user-images.githubusercontent.com/649340/31321251-25773dbc-ac83-11e7-94a2-5b7fb66cefc0.png)

For more details see pull request #426 :smile:.

**Comment by JasonLG1979** [comment]
That's how I would expect it to work. Looks good.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/5baa8d6c70149f0cec034837cb7d04e1cc1aba1f implements and closes this.
