### ISSUE TITLE
Indicator player state icon keeps disappearing

### ISSUE THREAD

**Issue by rrthomas** [JasonLG1979/gnome-shell-extensions-mediaplayer#429]
I have "Show the Indicator Player State Icon" ticked. Since I upgraded to version 61 of the extension, it keeps disappearing; toggling the option off and on makes it reappear.

I am using GNOME 3.18 (Ubuntu 16.04).

Thanks for this useful extension!

**Comment by lexruee** [comment]
@rrthomas 
Can your provide the steps or workflow to reproduce this bug? (Music Player etc.)

It sounds like that the following expression in the if condition [here](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/pull/427/files#diff-761c19a861be254b1425ba59c4454db2R116) becomes false at some point:

```js
let state = this.state;
    if (state.status && this._showPlayStateIcon) {
     ...
      this._secondaryIndicator.show();
      this._secondaryIndicator.set_width(-1);
      this.indicators.show();
    } else {
        this._secondaryIndicator.hide();
    }
```

**Comment by rrthomas** [comment]
The icon seems to disappear when the music stops (i.e. when the current playlist ends).

**Comment by JasonLG1979** [comment]
@rrthomas What player?

**Comment by rrthomas** [comment]
Cantata 2.2.0, with its built-in MPRIS support turned off.

**Comment by JasonLG1979** [comment]
> with its built-in MPRIS support turned off.

If MPRIS is disabled then ofc the player is going to disappear?

**Comment by rrthomas** [comment]
I don't understand. What does the icon have to do with Cantata?

**Comment by JasonLG1979** [comment]
This extension works via MPRIS. It is a MPRIS "client" where as the players are MPRIS "servers" If you disable MPRIS in the player it will make the player disappear from the extension.

**Comment by rrthomas** [comment]
Right, and I'm running mpDris2, sorry, I forgot to mention.

**Comment by JasonLG1979** [comment]
I would file a bug with mpDris2. Valid player states are represented by strings "Playing", "Paused", "Stopped". They may be sending an invalid or no value at all for "Stopped"?

**Comment by rrthomas** [comment]
What makes you suspect this? This used to work before the last update to this extension.

**Comment by rrthomas** [comment]
OK, I checked the source of mpDris2: it only sends "Playing", "Paused" or "Stopped".

**Comment by rrthomas** [comment]
Extra info: when the music stops (I also tried issuing `mpc stop`: same effect, as you'd hope!), the extension's icon (the headphones symbol) disappears, as well as the actual play state.

Meanwhile, mpDris2's MPRIS panel remains showing in the system menu.

**Comment by rrthomas** [comment]
W00t! Thanks!

**Comment by JasonLG1979** [comment]
Try the master branch and let me know if that does the trick. It makes sure "status" is never null hopefully. I think maybe you exposed an edge case? I don't think it's mpDris2's fault after all.

**Comment by rrthomas** [comment]
Doing it now…

**Comment by rrthomas** [comment]
I edited the patch to `player.js` in manually, and restarted ("r" command); result: no change.

**Comment by JasonLG1979** [comment]
That's strange. Now I'm going to have to install mpd, Cantata and mpDris2 and see if I can't figure this out...

**Comment by rrthomas** [comment]
OK, having managed to build current git, I confirm the same. I apologise for any harshing effect on your weekend's buzz.

**Comment by JasonLG1979** [comment]
> OK, having managed to build current git, I confirm the same. I apologise for any harshing effect on your weekend's buzz.

It's all good. This what I do for fun believe it or not. My day job is grease monkey.

**Comment by rrthomas** [comment]
Mine is singing for the Pope. I will now check the latest mpDris2 just in case.

**Comment by JasonLG1979** [comment]
> Mine is singing for the Pope

I have no idea what that means?

**Comment by rrthomas** [comment]
I meant it literally. Open mouth, breathe, exhale through vocal chords, Ad Maiorem Dei Gloriam in the local Catholic cathedral.

**Comment by rrthomas** [comment]
OK, have installed mpdris2-0.7+git20160917-1 (the latest version I can find packaged), and the result is exactly the same.

**Comment by JasonLG1979** [comment]
> I meant it literally. Open mouth, breathe, exhale through vocal chords, Ad Maiorem Dei Gloriam in the local Catholic cathedral.

I wasn't sure if that was some kinda slang,lol!!! Right on. I can't carry a tune in a bucket,lol!!! I do play a bad bass though.(when I say bad I mean not very good either...)

> OK, have installed mpdris2-0.7+git20160917-1 (the latest version I can find packaged), and the result is exactly the same.

I'm editing the wiki right now and I'll give it a test here sometime this weekend.

**Comment by rrthomas** [comment]
Yes, reading it back it does look like it could be something you'd find in Urban Dictionary.

**Comment by JasonLG1979** [comment]
> Yes, reading it back it does look like it could be something you'd find in Urban Dictionary.

Yes either some sort of lewd act or perhaps a position in a crime syndicate,lol!!!

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
