### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by rrthomas** [JasonLG1979/gnome-shell-extensions-mediaplayer#431]
$ ./build
    Error during basic setup:
    
    [Errno 2] No such file or directory: '/home/rrt/.local/var/repo/gnome-shell-extensions-mediaplayer/builddir'
    ninja: Entering directory `builddir'
    ninja: fatal: chdir to 'builddir' - No such file or directory
    Done

If I try `mkdir builddir` first, then I get:

    $ ./build
    A current build directory already exists. Would you like to remove it?
    1) Yes
    2) No
    #? 1
    Build directory was removed succesufly
    Error during basic setup:

(BTW, note "succesufly"!)

If I try answer 2, No, I get:

    The old build directory must be removed first. Exiting

**Comment by JasonLG1979** [comment]
Distro? What version of meson?

**Comment by rrthomas** [comment]
Ubuntu 16.04, meson 0.29.0 (as supplied with distro).

**Comment by JasonLG1979** [comment]
That's a way old version of meson. You can't really build anything with that,lol Sorry... You'll need at least 0.40.

**Comment by rrthomas** [comment]
Haha, I'm using a current LTS distro. That's really not my problem :)

**Comment by JasonLG1979** [comment]
It kinda is if you want to build any newer projects. A LOT of projects are moving to meson.

**Comment by rrthomas** [comment]
(This is one reason I use GNU autotools: I do not get bug reports like this!)

**Comment by rrthomas** [comment]
I am having a good day, so since I see there is a 16.04 backport of a new-enough version, I'm going to install it and carry on. But, using a build dep that is not in your users' distros is not a way to make friends, just sayin'!

**Comment by JasonLG1979** [comment]
Ubuntu LTS's are not the center of the universe. I don't target any distro specifically. I target GNOME versions.

**Comment by rrthomas** [comment]
Debian stable meson: 0.37. Ubuntu LTS 16.04: 0.29. Fedora 26: 0.39.

**Comment by rrthomas** [comment]
Confirm that once I've installed meson 0.40.1, I can build. Closing, and I'll add the version to the installation instructions; thanks for the tip!

**Comment by rrthomas** [comment]
I can't edit the wiki, it seems…

**Comment by JasonLG1979** [comment]
Meson is up to version 0.42 or 3 now in Fedora 26. It may have been 0.39 when Fedora 26 was released. Fedora doesn't freeze packages in the same way the Debian or Ubuntu does.

> I can't edit the wiki, it seems…

Yep, sorry about that I had a user edit the wiki asking for help one time...

**Comment by rrthomas** [comment]
The relevant incantation for Ubuntu 16.04 users is:

    sudo apt-get install -t xenial-backports meson

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
