### ISSUE TITLE
Support for Gnome Shell 3.26.1 and Ubuntu 17.10

### ISSUE THREAD

**Issue by GlenKPeterson** [JasonLG1979/gnome-shell-extensions-mediaplayer#434]
Your [Installation](https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/wiki/Installation) page only mentions Gnome shell up through 3.24 and Ubuntu through 16.04.  What about newer versions?  How do you get Banshee controls in the top bar now?

**Comment by JasonLG1979** [comment]
GNOME shell 3.26 is supported. The page just needs updating. The distro doesn't matter. You can install the extension at the GNOME Shell extensions site. Banshee is a dead project. There hasn't been a stable release in 3 years. It's very buggy. That being said you would need to enable MPRIS in Banshee.
