### ISSUE TITLE
Song information isn’t updated

### ISSUE THREAD

**Issue by fbruetting** [JasonLG1979/gnome-shell-extensions-mediaplayer#435]
I just listened to an album via Lollypop, then paused it (via middle-click on the status icon) and started playback of a file via Gnome-MPV (but I don’t know if I first paused the first and then started the second, or vice versa). Now what I see is the MPV icon, then a start/stop indicator (which works for Gnome-MPV) – but then the name of the current (paused) song of Lollypop.

Seems you have forgotten to reset all MPRIS object attributes (or whatever this is called) when players are changed…? (Maybe Gnome-MPV (Flatpak) or the file don’t emit tag information, which could also lead to skipping updating the song name?)

**Comment by JasonLG1979** [comment]
Those just so happen to be my choices for music and video payers also. Although I generally don't install the Flatpak versions. I'll see what the deal is and report back here in a bit.

**Comment by fbruetting** [comment]
Now I had the Gnome-MPV window still open, but deleted the file I played with it and pressed <play> on my keyboard. This led to the status icon being changed back to the Lollypop song – but the playback signal was sent to Gnome-MPV (of which I got of course an error displayed, due to the now missing file) and Lollypop never received the “play” signal.

I expect here no change of the status icon, because Gnome-MPV still was the active player.

**Comment by JasonLG1979** [comment]
@fbruetting does that work for you?

**Comment by fbruetting** [comment]
Have you seen my second writing? ;)

**Comment by JasonLG1979** [comment]
Yep that would be a different bug.

**Comment by fbruetting** [comment]
Should I file a new one?

**Comment by JasonLG1979** [comment]
Please.

**Comment by JasonLG1979** [comment]
This bug from what I can tell is that the panel text was not being updated correctly. My latest commit should fix that.

**Comment by fbruetting** [comment]
Oh, I deleted my file, I played with Gnome-MPV permanently… :/

**Comment by JasonLG1979** [comment]
Well that sucks, I'm sorry.

**Comment by fbruetting** [comment]
I’ll search my server…

**Comment by JasonLG1979** [comment]
Backups are your friend. I personally have triple local redundancy plus offsite.

**Comment by fbruetting** [comment]
Yeah, this was my backup – because I don’t need it anymore. :P
So I can’t reproduce it, but I’ll write you, if I see this again!

**Comment by JasonLG1979** [comment]
I mostly use my backups for media. I have like 600 movies ripped(that I own so it's legal as much as the MPA would have you not believe.) That I use with a Plex server and a couple Rokus to make sure my kids don't scratch up the discs. I don't want to rip them all over again. I had a drive fail at the 200 movie mark and I said never again. Ripping 600 movies would take weeks...

**Comment by fbruetting** [comment]
I got a FreeNAS with Raid-Z1 for media & backups on mirrored disks, but use Kodi on a dedicated HTPC. FreeBSD with ZFS is the best you can get for servers or NAS systems! :)

**Comment by JasonLG1979** [comment]
> FreeBSD with ZFS is the best you can get for servers or NAS systems! :)

I'm not going to argue with that. I don't have a NAS, just a few TB's of USB hard drives and the Plex server. The Plex server just does Plex, that's it. I use sshfs to transfer files to it manually.
