### ISSUE TITLE
Progress indicator in the status bar?

### ISSUE THREAD

**Issue by j4cobgarby** [JasonLG1979/gnome-shell-extensions-mediaplayer#438]
First of all - really cool extension!

One thing I think would add to it is if in the status bar there was some way of seeing how far through the currently playing song I am, so this could be something like just displaying it as a time, or maybe even a progress bar.

I'd be happy to try and do this - it'll be an excuse for me to learn how to do these things - if no one else wants to, and if you think it'd be a good addition.

**Comment by JasonLG1979** [comment]
See:
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/98754b7a6902d7fbc4652968bcafdaeefba47cf8

You can already display the media's time in the panel by adding``` {trackPosition} / {trackDuration}``` to the Indicator Status Text.

**Comment by JasonLG1979** [comment]
To expand on that:
```{trackArtist - }{trackTitle | }{trackPosition / }{trackDuration}```
Would get you something like this:
![screenshot from 2017-12-25 06-50-21](https://user-images.githubusercontent.com/6667703/34339887-09361aac-e940-11e7-9a99-5f48519f48d9.png)

In that case the -, |, / only show up if their fields exist since they follow the field name but are inside the {}'s.

**Comment by j4cobgarby** [comment]
Oh! Thanks. That didn't appear to be in the Wiki

**Comment by JasonLG1979** [comment]
> Oh! Thanks. That didn't appear to be in the Wiki

I'll update it. But for the most part you can put any field name in the panel from:
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/src/player.js#L52-L110

But most are probability not very useful...
