### ISSUE TITLE
Play / Next / Previous buttons in Title Bar

### ISSUE THREAD

**Issue by vallant** [JasonLG1979/gnome-shell-extensions-mediaplayer#441]
Hello, i'd like to know if its possible to put some of the control buttons into the top bar?

**Comment by JasonLG1979** [comment]
You can already use your mouse wheel. Wheel up = next, Wheel down = previous, Wheel press = Play/Pause.

**Comment by Vallant** [comment]
Im working a lot on my laptop without a mouse, so it would be great to
have an option to enable buttons for these functions too, in addition
to the mouse wheel!

**Comment by JasonLG1979** [comment]
I'm sorry but I'm not to keen on the idea of adding more to the panel, especially buttons. The mouse wheel is just button 2(by default). Whatever gesture you use on your trackpad to scroll or middle click would do the same thing as an actual physical mouse wheel.

**Comment by Vallant** [comment]
Is there a specific reason to that? If the user enables the display of the 
song and artist, the panel is already quite big. I was of course just 
talking about making it optional to enable the buttons.

I know that its possible with a trackpad too, but in my opinion this is a 
bit unintuitive- even with a mouse!

**Comment by JasonLG1979** [comment]
You are more then welcome to put in a Pull Request and we will go from there.
