### ISSUE TITLE
Integration Telegram Desktop

### ISSUE THREAD

**Issue by orschiro** [JasonLG1979/gnome-shell-extensions-mediaplayer#442]
Hey @JasonLG1979,

Thanks so much for this brilliant extension. Love it. Became my daily driver. :-)

Question, I like listening to music via Telegram Desktop (have some saved messages there). 

Is it somehow possible to integrate TG with your extension?

Thanks!

**Comment by JasonLG1979** [comment]
That's not how MPRIS clients work. The client doesn't enable support for any player or the like. They would have to expose a MPRIS interface.

**Comment by orschiro** [comment]
Thanks Jason! Cross-referencing my own thread regarding this which I had actually forgotten about. :-D

https://github.com/telegramdesktop/tdesktop/issues/3960

I guess we can close this one then...
