### ISSUE TITLE
Any way to reverse the scrolling behaviour?

### ISSUE THREAD

**Issue by pwd-github** [JasonLG1979/gnome-shell-extensions-mediaplayer#446]
Scrolling up rewinds and scrolling down forwards the track. That's different to what other players do, any way to reverse that behaviour to match what users would expect?

**Comment by JasonLG1979** [comment]
Yep, I can reverse that. It's just the way it's always been. I thought it was kinda strange myself.

**Comment by JasonLG1979** [comment]
Done.

**Comment by pwd-github** [comment]
You're brilliant! Thank you very much @JasonLG1979
