### ISSUE TITLE
Hide extension icon

### ISSUE THREAD

**Issue by XPanniX** [JasonLG1979/gnome-shell-extensions-mediaplayer#447]
Is there a way to hide the extension icon so that only the indicator status text is shown?  
So that:  
![image](https://user-images.githubusercontent.com/1346944/37454183-2b697cf2-283a-11e8-865a-e6b0ad1c6753.png)
  
Becomes:  
![image](https://user-images.githubusercontent.com/1346944/37454202-39070f1e-283a-11e8-94c8-e404f0d465bd.png)

**Comment by JasonLG1979** [comment]
No because the status text is user defined and by default blank. No icon + no text = nothing to serve as a button.

**Comment by XPanniX** [comment]
What about hiding it when text is displayed (a song is playing)?

**Comment by JasonLG1979** [comment]
I'm OK with that. I'd be willing to review any pull requests that adds that option.

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
