### ISSUE TITLE
Add Logitech Media Server to the list of compatible players

### ISSUE THREAD

**Issue by mavit** [JasonLG1979/gnome-shell-extensions-mediaplayer#450]
As I understand it, GitHub doesn't support pull requests against a project's wiki, so...

```
commit 7910b8e2cae2f14cdd7462678af84abc6197e424 (HEAD -> master)
Author: Peter Oliver <git@mavit.org.uk>
Date:   Wed Apr 18 16:57:43 2018 +0100

    Add slimpris2 to list of compatible players

diff --git a/Compatible-players.md b/Compatible-players.md
index 51d25f0..0739aac 100644
--- a/Compatible-players.md
+++ b/Compatible-players.md
@@ -20,6 +20,7 @@ This extension has been tested with:
   * GNOME Music
   * Guayadeque (≥ 0.3.2)
   * JuK
+  * Logitech Media Server (with [slimpris2](https://github.com/mavit/slimpris2) daemon)
   * mpd (with [mpDris2](https://github.com/eonpatapon/mpDris2) daemon)
   * Nuvola *aka* Google Music Frame
   * Pithos
```

**Comment by JasonLG1979** [comment]
Well I could set the wiki to be editable by anyone. But in one of my repos (I can't remember if it was this one or not?) I actually had someone ask for help/try to file a bug by editing the wiki. So anymore I only allow editing by "Contributors", and myself ofc.

But to the point. Normally if you were talking about "Yet another Linux music player" I'd probably say that "and more..." would cover it, but I think that the Logitech Media Server/slimpris2 combo warrants a mention. I'll add it.

**Comment by JasonLG1979** [comment]
Done.
