### ISSUE TITLE
no track duration for added tracks

### ISSUE THREAD

**Issue by roizcorp** [JasonLG1979/gnome-shell-extensions-mediaplayer#458]
So I actually think this is mpDris2 issue, but I have no clue really.
The scenario is add a track which is not in the music_directory i.e. mpc add "some uri"

when you play it, the media player indicator sticks on "0:00" duration while gmpc, and mpc status show the real duration

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
