### ISSUE TITLE
Extra space appears after status text 

### ISSUE THREAD

**Issue by arngo** [JasonLG1979/gnome-shell-extensions-mediaplayer#462]
When the indicator is reloaded (i.e. when changing the position (left/center/right/system menu), locking/unlocking the screen, reloading the extension), an extra margin appears to the right of the status text if it is set. This is much more noticeable on the Adapta shell theme than it is on the default, where only a few pixels might appear. 

This only seems to occur when the status text does not reach the set maximum width, i.e "Indicator Status Text Width", and when there is only one player running. The problem goes away when the next song starts playing or when the status text format is changed.

This issue started with this commit: https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/commit/71e44f9b7f49acc4c9908b11ea00f69b8cc922c2

Distro: Arch Linux
GNOME Shell version 3.30.2
Players tested: Quodlibet and Lollypop
Extension version: Current git master

**Comment by JasonLG1979** [comment]
I just tested on the Adapta theme and without the text being truncated I get 15px of padding no matter what.

![screenshot from 2018-11-21 19-08-23](https://user-images.githubusercontent.com/6667703/48876009-a6efbb00-edc1-11e8-8933-126f27af3fcc.png)
![screenshot from 2018-11-21 19-07-42](https://user-images.githubusercontent.com/6667703/48876010-a6efbb00-edc1-11e8-8b66-d21fcda1e34e.png)
![screenshot from 2018-11-21 19-07-31](https://user-images.githubusercontent.com/6667703/48876011-a7885180-edc1-11e8-91d0-f1357e478949.png)

**Comment by JasonLG1979** [comment]
What is the content exactly of the Indicator Status Text.

**Comment by arngo** [comment]
I have it as `{trackArtist  •  }{trackTitle}`

**Comment by JasonLG1979** [comment]
That's correct formatting, btw like the dot. I was wondering if you had any whitespace between the curlies and you don't so that's good. I'll play with some more after Thanksgiving and see if I can reproduce the issue.

**Comment by arngo** [comment]
Alright, thanks. Have a good holiday!

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
