### ISSUE TITLE
No Animations in tray

### ISSUE THREAD

**Issue by Appadeia** [JasonLG1979/gnome-shell-extensions-mediaplayer#472]
Self explanatory. The multimedia player lacks tray animations unlike the other widgets there.
Video showing off what I mean: https://youtu.be/kmuHry8yg-Y
Version is the latest one from the extensions site

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
