### ISSUE TITLE
Align the popup to the left

### ISSUE THREAD

**Issue by fbruetting** [JasonLG1979/gnome-shell-extensions-mediaplayer#473]
Hi @JasonLG1979!

The popup currently is centered and thus changes its position every time the track in changing. Would you like to align that to the left, maybe with some fixed offset?

![bildschirmfoto von 2019-02-19 00-55-46](https://user-images.githubusercontent.com/10520767/52981694-885d8800-33e1-11e9-8053-0ab6dbf91f7a.png)
![bildschirmfoto von 2019-02-19 00-58-38](https://user-images.githubusercontent.com/10520767/52981701-901d2c80-33e1-11e9-814e-63d89621ee1a.png)

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
