### ISSUE TITLE
This extension is set to be retired

### ISSUE THREAD

**Issue by JasonLG1979** [JasonLG1979/gnome-shell-extensions-mediaplayer#478]
I will not be releasing any newer versions of this extension. That does not necessarily mean the code will disappear. It is opensource after all, anyone and everyone can fork it and do whatever they like, or for that matter someone is more than welcome to take ownership of this repo.

My plan is instead to port some of it's features over to https://github.com/JasonLG1979/gnome-shell-extension-mpris-indicator-button The reason being is that updating this extension would basically amount to a rewrite anyway so I'd rather just start with a cleaner code base.

A few guidelines:

1. The extension will have no user configurable options. Instead there will sane defaults.
2. The extension will have no user visible strings that require translation.
3. The extension will stay out of the system menu.
4. The extension will avoid visual clutter.

I opened this issue to get feedback so I know what features that users care about and meet the above guidelines.

**Comment by pwd-github** [comment]
Thank you for everything and good luck. I hope that someone forks your retwrite and stuffs it into the system menu as that was the very reason I chose your extension over others.

**Comment by roizcorp** [comment]
I'd like to thank you for all the work you've done, I'm pretty sure this extension is the first one I used and it is awesome still. You've been very helpful with my feature requests and I hope either Gnome will embed the idea in to the product or someone will step up and will rewrite it.

Personally, I think the best thing about it was displaying the current song, artist, album and elapsed time on the top bar, all the other stuff were bonus goodies.

Good luck ahead!

**Comment by JasonLG1979** [comment]
> I'd like to thank you for all the work you've done, I'm pretty sure this extension is the first one I used and it is awesome still. You've been very helpful with my feature requests and I hope either Gnome will embed the idea in to the product or someone will step up and will rewrite it.

You're welcome.

The problems with this extension as I see them:

1. It's a very old code base and could use A LOT of modernizing and cleanup.
2. There are way to many options. That adds a lot of complexity and makes maintaining it difficult.
3. It requires fragile hacks to make the widgets appear and function as desired even then it still doesn't look quite and they break often with new Shell versions.

> Personally, I think the best thing about it was displaying the current song, artist, album and elapsed time on the top bar, all the other stuff were bonus goodies.

I like the song info in the panel also but many seem to not or at least not care about it. I'm trying to find a compromise sane default. Maybe having the info shown in the panel or in a "Tooltip" upon hovering over the icon? I'm not sure yet. That's what this all about, I'm trying to figure out what features people actually use. But if you and I are the only ones who like the info in the panel and everyone else is like "meh" or "I hate that" it won't make the cut.

In a way this is about trading in that luxury sports car that needs constant tuning and maintenance for a daily driver that although may not have all the bells and whistles, just works reliably all the time.  

As far as elapsed time or dealing with track position at all, that's not going to happen with the new extension. Anything to do with track position or seeking and whatnot is easily the weakest part of about every player's MPRIS implementation. It's just too buggy.

**Comment by roizcorp** [comment]
> > Personally, I think the best thing about it was displaying the current song, artist, album and elapsed time on the top bar, all the other stuff were bonus goodies.
> 
> I like the song info in the panel also but many seem to not or at least not care about it. I'm trying to find a compromise sane default. Maybe having the info shown in the panel or in a "Tooltip" upon hovering over the icon? I'm not sure yet. That's what this all about, I'm trying to figure out what features people actually use. But if you and I are the only ones who like the info in the panel and everyone else is like "meh" or "I hate that" it won't make the cut.

I understand but it is not that Github has an up-voting system like we use in Product Management, my vote is panel as tooltip will require me actively check when hover.

> As far as elapsed time or dealing with track position at all, that's not going to happen with the new extension. Anything to do with track position or seeking and whatnot is easily the weakest part of about every player's MPRIS implementation. It's just too buggy.

Thought so...I suppose it's better to keep thin and healthy even in software


The problems with this extension as I see them:

    It's a very old code base and could use A LOT of modernizing and cleanup.
>    There are way to many options. That adds a lot of complexity and makes maintaining it difficult.
Agree, while looking at the option menu, 80%-90% of the features I don't even use...but I have a very specific use case (MPD)
>    It requires fragile hacks to make the widgets appear and function as desired even then it still doesn't look quite and they break often with new Shell versions.
> Best thing it keep what's working w/o hacks, even if they are easy to hack, these kind of things a "long tailing" each release.

I see issue #477 has some commits, are those commits indeed efforts for rewrite?

**Comment by JasonLG1979** [comment]
> I understand but it is not that Github has an up-voting system like we use in Product Management

This is pretty informal. A conversation will do I think. I don't see this as a real "product" as it's not developed by a company and certainly not for any real absolutely needed utility. It's just a little widget, a bit of eye candy. It's a hobby for me and likely the same for anyone who would take it over if they do. In a few weeks I will close this issue and archive the repo if no one wants to take it over and that will be that.

 > my vote is panel as tooltip will require me actively check when hover.

I know not really that useful and GNOME Shell has no real builtin easy way for tooltips so again I don't know?

> I see issue #477 has some commits, are those commits indeed efforts for rewrite?

That's the bare minimum to make it not crash on 3.32. It's hardly a rewrite.

**Comment by JasonLG1979** [comment]
Well times up. There will be no further updates unless someone decides to take over maintainership of this repo and the extension at https://extensions.gnome.org/extension/55/media-player-indicator/

**Comment by hackel** [comment]
Thanks for your work on this.  For what it's worth, I love the idea of a simple extension with sane defaults and few options, though I do prefer it in the system menu in order to de-clutter my top bar.  I wish Gnome Shell would adopt an option similar to Firefox, where you can right-click on any extension and "Pin to overflow/system menu."

**Comment by JasonLG1979** [comment]
> I love the idea of a simple extension with sane defaults and few options, though I do prefer it in the system menu in order to de-clutter my top bar.

Anywhere besides the clock/calendar/message area IMHO. I mean I kinda get notifications being in the clock next to the calendar as they may be time sensitive and/or schedule related, but not media player controls. Media player controls aren't notifications in the traditional sense.

The reasons for putting the controls in a panel button and not in the system menu:

1. There is *usually* plenty of space in the panel. Ofc your mileage may (and apparently does) vary.

2. The panel (system tray) is traditionally where players of old would put their tray icons.

3. The system menu can very quickly become cluttered also, even by default depending on how many menus/items are visible it can be very busy visually.

4. If the controls were in the system menu IMHO the best place for them would right after the separator below the system volume, but there's really no way to reliably make sure that's where it ends up. There's no foolproof way to call dibs on that spot.

> I wish Gnome Shell would adopt an option similar to Firefox, where you can right-click on any extension and "Pin to overflow/system menu."

I'd love to have an "edit" mode for the Shell that allowed you to arbitrarily move things around like in a bunch other DE's.
