### ISSUE TITLE
Don't work on fedora 30

### ISSUE THREAD

**Issue by adian** [JasonLG1979/gnome-shell-extensions-mediaplayer#480]
Can't install on fedora 30. `Error loading extension`

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer#this-extension-has-been-retired

**Comment by JasonLG1979** [comment]
https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/README.md
